// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: payze.proto

package integration_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PayzeServiceClient is the client API for PayzeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayzeServiceClient interface {
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error)
	UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*UpdateTransactionResponse, error)
	GetPayzeInfo(ctx context.Context, in *GetPayzeInfoRequest, opts ...grpc.CallOption) (*GetPayzeInfoResponse, error)
}

type payzeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayzeServiceClient(cc grpc.ClientConnInterface) PayzeServiceClient {
	return &payzeServiceClient{cc}
}

func (c *payzeServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error) {
	out := new(CreateTransactionResponse)
	err := c.cc.Invoke(ctx, "/integration_service.PayzeService/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payzeServiceClient) UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*UpdateTransactionResponse, error) {
	out := new(UpdateTransactionResponse)
	err := c.cc.Invoke(ctx, "/integration_service.PayzeService/UpdateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payzeServiceClient) GetPayzeInfo(ctx context.Context, in *GetPayzeInfoRequest, opts ...grpc.CallOption) (*GetPayzeInfoResponse, error) {
	out := new(GetPayzeInfoResponse)
	err := c.cc.Invoke(ctx, "/integration_service.PayzeService/GetPayzeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayzeServiceServer is the server API for PayzeService service.
// All implementations must embed UnimplementedPayzeServiceServer
// for forward compatibility
type PayzeServiceServer interface {
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	UpdateTransaction(context.Context, *UpdateTransactionRequest) (*UpdateTransactionResponse, error)
	GetPayzeInfo(context.Context, *GetPayzeInfoRequest) (*GetPayzeInfoResponse, error)
	mustEmbedUnimplementedPayzeServiceServer()
}

// UnimplementedPayzeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPayzeServiceServer struct {
}

func (UnimplementedPayzeServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedPayzeServiceServer) UpdateTransaction(context.Context, *UpdateTransactionRequest) (*UpdateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransaction not implemented")
}
func (UnimplementedPayzeServiceServer) GetPayzeInfo(context.Context, *GetPayzeInfoRequest) (*GetPayzeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayzeInfo not implemented")
}
func (UnimplementedPayzeServiceServer) mustEmbedUnimplementedPayzeServiceServer() {}

// UnsafePayzeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayzeServiceServer will
// result in compilation errors.
type UnsafePayzeServiceServer interface {
	mustEmbedUnimplementedPayzeServiceServer()
}

func RegisterPayzeServiceServer(s grpc.ServiceRegistrar, srv PayzeServiceServer) {
	s.RegisterService(&PayzeService_ServiceDesc, srv)
}

func _PayzeService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayzeServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integration_service.PayzeService/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayzeServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayzeService_UpdateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayzeServiceServer).UpdateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integration_service.PayzeService/UpdateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayzeServiceServer).UpdateTransaction(ctx, req.(*UpdateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayzeService_GetPayzeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayzeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayzeServiceServer).GetPayzeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integration_service.PayzeService/GetPayzeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayzeServiceServer).GetPayzeInfo(ctx, req.(*GetPayzeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayzeService_ServiceDesc is the grpc.ServiceDesc for PayzeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayzeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration_service.PayzeService",
	HandlerType: (*PayzeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _PayzeService_CreateTransaction_Handler,
		},
		{
			MethodName: "UpdateTransaction",
			Handler:    _PayzeService_UpdateTransaction_Handler,
		},
		{
			MethodName: "GetPayzeInfo",
			Handler:    _PayzeService_GetPayzeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payze.proto",
}
