// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: offline_appointment.proto

package registration_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfflineAppointment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date            string `protobuf:"bytes,1,opt,name=date,proto3" json:"date"`
	PatientFullName string `protobuf:"bytes,2,opt,name=patient_full_name,json=patientFullName,proto3" json:"patient_full_name"`
	OverallPrice    string `protobuf:"bytes,3,opt,name=overall_price,json=overallPrice,proto3" json:"overall_price"`
	PaymentStatus   string `protobuf:"bytes,4,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status"`
	RegistratorName string `protobuf:"bytes,5,opt,name=registrator_name,json=registratorName,proto3" json:"registrator_name"`
}

func (x *OfflineAppointment) Reset() {
	*x = OfflineAppointment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offline_appointment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineAppointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineAppointment) ProtoMessage() {}

func (x *OfflineAppointment) ProtoReflect() protoreflect.Message {
	mi := &file_offline_appointment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineAppointment.ProtoReflect.Descriptor instead.
func (*OfflineAppointment) Descriptor() ([]byte, []int) {
	return file_offline_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *OfflineAppointment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *OfflineAppointment) GetPatientFullName() string {
	if x != nil {
		return x.PatientFullName
	}
	return ""
}

func (x *OfflineAppointment) GetOverallPrice() string {
	if x != nil {
		return x.OverallPrice
	}
	return ""
}

func (x *OfflineAppointment) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *OfflineAppointment) GetRegistratorName() string {
	if x != nil {
		return x.RegistratorName
	}
	return ""
}

type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offline_appointment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offline_appointment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_offline_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePaymentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllOfflineAppointmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfflineAppointments []*OfflineAppointment `protobuf:"bytes,1,rep,name=offline_appointments,json=offlineAppointments,proto3" json:"offline_appointments"`
	Count               int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
}

func (x *GetAllOfflineAppointmentsResponse) Reset() {
	*x = GetAllOfflineAppointmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offline_appointment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOfflineAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOfflineAppointmentsResponse) ProtoMessage() {}

func (x *GetAllOfflineAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offline_appointment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOfflineAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllOfflineAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_offline_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllOfflineAppointmentsResponse) GetOfflineAppointments() []*OfflineAppointment {
	if x != nil {
		return x.OfflineAppointments
	}
	return nil
}

func (x *GetAllOfflineAppointmentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OfflineAppointmentGroupedByDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date                string                `protobuf:"bytes,1,opt,name=date,proto3" json:"date"`
	OfflineAppointments []*OfflineAppointment `protobuf:"bytes,2,rep,name=offline_appointments,json=offlineAppointments,proto3" json:"offline_appointments"`
}

func (x *OfflineAppointmentGroupedByDate) Reset() {
	*x = OfflineAppointmentGroupedByDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offline_appointment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineAppointmentGroupedByDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineAppointmentGroupedByDate) ProtoMessage() {}

func (x *OfflineAppointmentGroupedByDate) ProtoReflect() protoreflect.Message {
	mi := &file_offline_appointment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineAppointmentGroupedByDate.ProtoReflect.Descriptor instead.
func (*OfflineAppointmentGroupedByDate) Descriptor() ([]byte, []int) {
	return file_offline_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineAppointmentGroupedByDate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *OfflineAppointmentGroupedByDate) GetOfflineAppointments() []*OfflineAppointment {
	if x != nil {
		return x.OfflineAppointments
	}
	return nil
}

type GetAllOfflineAppointmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search    string `protobuf:"bytes,1,opt,name=search,proto3" json:"search"`
	BranchId  string `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id"`
	Date      string `protobuf:"bytes,3,opt,name=date,proto3" json:"date"`
	PatientId string `protobuf:"bytes,4,opt,name=patient_id,json=patientId,proto3" json:"patient_id"`
	DoctorId  string `protobuf:"bytes,5,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id"`
	ServiceId string `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id"`
}

func (x *GetAllOfflineAppointmentsRequest) Reset() {
	*x = GetAllOfflineAppointmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offline_appointment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOfflineAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOfflineAppointmentsRequest) ProtoMessage() {}

func (x *GetAllOfflineAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offline_appointment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOfflineAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllOfflineAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_offline_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllOfflineAppointmentsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllOfflineAppointmentsRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *GetAllOfflineAppointmentsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetAllOfflineAppointmentsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *GetAllOfflineAppointmentsRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *GetAllOfflineAppointmentsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type OfflineAppointmentPrimaryKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
}

func (x *OfflineAppointmentPrimaryKey) Reset() {
	*x = OfflineAppointmentPrimaryKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offline_appointment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineAppointmentPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineAppointmentPrimaryKey) ProtoMessage() {}

func (x *OfflineAppointmentPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_offline_appointment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineAppointmentPrimaryKey.ProtoReflect.Descriptor instead.
func (*OfflineAppointmentPrimaryKey) Descriptor() ([]byte, []int) {
	return file_offline_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *OfflineAppointmentPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_offline_appointment_proto protoreflect.FileDescriptor

var file_offline_appointment_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0xcb, 0x01, 0x0a, 0x12, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x76, 0x65, 0x72,
	0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x2c, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x96, 0x01,
	0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x14, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x61,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x13, 0x6f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x1f, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x65, 0x64, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x5b,
	0x0a, 0x14, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x13, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xc6, 0x01, 0x0a, 0x20,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x1c, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x32, 0x99, 0x01, 0x0a, 0x19, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x7c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x2e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_offline_appointment_proto_rawDescOnce sync.Once
	file_offline_appointment_proto_rawDescData = file_offline_appointment_proto_rawDesc
)

func file_offline_appointment_proto_rawDescGZIP() []byte {
	file_offline_appointment_proto_rawDescOnce.Do(func() {
		file_offline_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(file_offline_appointment_proto_rawDescData)
	})
	return file_offline_appointment_proto_rawDescData
}

var file_offline_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_offline_appointment_proto_goTypes = []interface{}{
	(*OfflineAppointment)(nil),                // 0: registration_service.OfflineAppointment
	(*UpdatePaymentStatusRequest)(nil),        // 1: registration_service.UpdatePaymentStatusRequest
	(*GetAllOfflineAppointmentsResponse)(nil), // 2: registration_service.GetAllOfflineAppointmentsResponse
	(*OfflineAppointmentGroupedByDate)(nil),   // 3: registration_service.OfflineAppointmentGroupedByDate
	(*GetAllOfflineAppointmentsRequest)(nil),  // 4: registration_service.GetAllOfflineAppointmentsRequest
	(*OfflineAppointmentPrimaryKey)(nil),      // 5: registration_service.OfflineAppointmentPrimaryKey
}
var file_offline_appointment_proto_depIdxs = []int32{
	0, // 0: registration_service.GetAllOfflineAppointmentsResponse.offline_appointments:type_name -> registration_service.OfflineAppointment
	0, // 1: registration_service.OfflineAppointmentGroupedByDate.offline_appointments:type_name -> registration_service.OfflineAppointment
	4, // 2: registration_service.OfflineAppointmentService.GetList:input_type -> registration_service.GetAllOfflineAppointmentsRequest
	2, // 3: registration_service.OfflineAppointmentService.GetList:output_type -> registration_service.GetAllOfflineAppointmentsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_offline_appointment_proto_init() }
func file_offline_appointment_proto_init() {
	if File_offline_appointment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_offline_appointment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineAppointment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offline_appointment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePaymentStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offline_appointment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOfflineAppointmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offline_appointment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineAppointmentGroupedByDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offline_appointment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOfflineAppointmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offline_appointment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineAppointmentPrimaryKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_offline_appointment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offline_appointment_proto_goTypes,
		DependencyIndexes: file_offline_appointment_proto_depIdxs,
		MessageInfos:      file_offline_appointment_proto_msgTypes,
	}.Build()
	File_offline_appointment_proto = out.File
	file_offline_appointment_proto_rawDesc = nil
	file_offline_appointment_proto_goTypes = nil
	file_offline_appointment_proto_depIdxs = nil
}
