// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pg_csv.proto

package new_object_builder_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pg_csv_proto protoreflect.FileDescriptor

const file_pg_csv_proto_rawDesc = "" +
	"\n" +
	"\fpg_csv.proto\x12\x1anew_object_builder_service\x1a\x17pg_object_builder.proto2t\n" +
	"\n" +
	"CSVService\x12f\n" +
	"\fGetListInCSV\x12).new_object_builder_service.CommonMessage\x1a).new_object_builder_service.CommonMessage\"\x00B%Z#genproto/new_object_builder_serviceb\x06proto3"

var file_pg_csv_proto_goTypes = []any{
	(*CommonMessage)(nil), // 0: new_object_builder_service.CommonMessage
}
var file_pg_csv_proto_depIdxs = []int32{
	0, // 0: new_object_builder_service.CSVService.GetListInCSV:input_type -> new_object_builder_service.CommonMessage
	0, // 1: new_object_builder_service.CSVService.GetListInCSV:output_type -> new_object_builder_service.CommonMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pg_csv_proto_init() }
func file_pg_csv_proto_init() {
	if File_pg_csv_proto != nil {
		return
	}
	file_pg_object_builder_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pg_csv_proto_rawDesc), len(file_pg_csv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pg_csv_proto_goTypes,
		DependencyIndexes: file_pg_csv_proto_depIdxs,
	}.Build()
	File_pg_csv_proto = out.File
	file_pg_csv_proto_goTypes = nil
	file_pg_csv_proto_depIdxs = nil
}
