// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pg_function.proto

package new_object_builder_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFunctionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProjectId        string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	VersionId        string                 `protobuf:"bytes,5,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	CommitId         string                 `protobuf:"bytes,6,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CommitGuid       string                 `protobuf:"bytes,7,opt,name=commit_guid,json=commitGuid,proto3" json:"commit_guid,omitempty"`
	EnvironmentId    string                 `protobuf:"bytes,8,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	FunctionFolderId string                 `protobuf:"bytes,9,opt,name=function_folder_id,json=functionFolderId,proto3" json:"function_folder_id,omitempty"`
	Url              string                 `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty"`
	Password         string                 `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	SshUrl           string                 `protobuf:"bytes,12,opt,name=ssh_url,json=sshUrl,proto3" json:"ssh_url,omitempty"`
	Type             string                 `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	FrameworkType    string                 `protobuf:"bytes,16,opt,name=framework_type,json=frameworkType,proto3" json:"framework_type,omitempty"`
	GitlabId         string                 `protobuf:"bytes,14,opt,name=gitlab_id,json=gitlabId,proto3" json:"gitlab_id,omitempty"`
	GitlabGroupId    string                 `protobuf:"bytes,15,opt,name=gitlab_group_id,json=gitlabGroupId,proto3" json:"gitlab_group_id,omitempty"`
	SourceUrl        string                 `protobuf:"bytes,17,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	PipelineStatus   string                 `protobuf:"bytes,18,opt,name=pipeline_status,json=pipelineStatus,proto3" json:"pipeline_status,omitempty"`
	Branch           string                 `protobuf:"bytes,19,opt,name=branch,proto3" json:"branch,omitempty"`
	RepoId           string                 `protobuf:"bytes,20,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,21,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	JobName          string                 `protobuf:"bytes,22,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Resource         string                 `protobuf:"bytes,23,opt,name=resource,proto3" json:"resource,omitempty"`
	ProvidedName     string                 `protobuf:"bytes,24,opt,name=provided_name,json=providedName,proto3" json:"provided_name,omitempty"`
	IsPublic         bool                   `protobuf:"varint,25,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	MaxScale         int32                  `protobuf:"varint,26,opt,name=max_scale,json=maxScale,proto3" json:"max_scale,omitempty"`
	FormerMaxScale   int32                  `protobuf:"varint,27,opt,name=former_max_scale,json=formerMaxScale,proto3" json:"former_max_scale,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	mi := &file_pg_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFunctionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFunctionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFunctionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateFunctionRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *CreateFunctionRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CreateFunctionRequest) GetCommitGuid() string {
	if x != nil {
		return x.CommitGuid
	}
	return ""
}

func (x *CreateFunctionRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CreateFunctionRequest) GetFunctionFolderId() string {
	if x != nil {
		return x.FunctionFolderId
	}
	return ""
}

func (x *CreateFunctionRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateFunctionRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateFunctionRequest) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *CreateFunctionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFunctionRequest) GetFrameworkType() string {
	if x != nil {
		return x.FrameworkType
	}
	return ""
}

func (x *CreateFunctionRequest) GetGitlabId() string {
	if x != nil {
		return x.GitlabId
	}
	return ""
}

func (x *CreateFunctionRequest) GetGitlabGroupId() string {
	if x != nil {
		return x.GitlabGroupId
	}
	return ""
}

func (x *CreateFunctionRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *CreateFunctionRequest) GetPipelineStatus() string {
	if x != nil {
		return x.PipelineStatus
	}
	return ""
}

func (x *CreateFunctionRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *CreateFunctionRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateFunctionRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CreateFunctionRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CreateFunctionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreateFunctionRequest) GetProvidedName() string {
	if x != nil {
		return x.ProvidedName
	}
	return ""
}

func (x *CreateFunctionRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CreateFunctionRequest) GetMaxScale() int32 {
	if x != nil {
		return x.MaxScale
	}
	return 0
}

func (x *CreateFunctionRequest) GetFormerMaxScale() int32 {
	if x != nil {
		return x.FormerMaxScale
	}
	return 0
}

type Function struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ProjectId        string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FunctionFolderId string                 `protobuf:"bytes,7,opt,name=function_folder_id,json=functionFolderId,proto3" json:"function_folder_id,omitempty"`
	EnvironmentId    string                 `protobuf:"bytes,8,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Url              string                 `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Password         string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	SshUrl           string                 `protobuf:"bytes,11,opt,name=ssh_url,json=sshUrl,proto3" json:"ssh_url,omitempty"`
	Type             string                 `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	GitlabId         string                 `protobuf:"bytes,13,opt,name=gitlab_id,json=gitlabId,proto3" json:"gitlab_id,omitempty"`
	GitlabGroupId    string                 `protobuf:"bytes,14,opt,name=gitlab_group_id,json=gitlabGroupId,proto3" json:"gitlab_group_id,omitempty"`
	FrameworkType    string                 `protobuf:"bytes,15,opt,name=framework_type,json=frameworkType,proto3" json:"framework_type,omitempty"`
	SourceUrl        string                 `protobuf:"bytes,16,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	PipelineStatus   string                 `protobuf:"bytes,17,opt,name=pipeline_status,json=pipelineStatus,proto3" json:"pipeline_status,omitempty"`
	Branch           string                 `protobuf:"bytes,18,opt,name=branch,proto3" json:"branch,omitempty"`
	RepoId           string                 `protobuf:"bytes,19,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,20,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	JobName          string                 `protobuf:"bytes,21,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Resource         string                 `protobuf:"bytes,22,opt,name=resource,proto3" json:"resource,omitempty"`
	ProvidedName     string                 `protobuf:"bytes,23,opt,name=provided_name,json=providedName,proto3" json:"provided_name,omitempty"`
	RequestType      string                 `protobuf:"bytes,24,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	IsPublic         bool                   `protobuf:"varint,25,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	MaxScale         int32                  `protobuf:"varint,26,opt,name=max_scale,json=maxScale,proto3" json:"max_scale,omitempty"`
	FormerMaxScale   int32                  `protobuf:"varint,27,opt,name=former_max_scale,json=formerMaxScale,proto3" json:"former_max_scale,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_pg_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{1}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Function) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Function) GetFunctionFolderId() string {
	if x != nil {
		return x.FunctionFolderId
	}
	return ""
}

func (x *Function) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *Function) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Function) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Function) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *Function) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Function) GetGitlabId() string {
	if x != nil {
		return x.GitlabId
	}
	return ""
}

func (x *Function) GetGitlabGroupId() string {
	if x != nil {
		return x.GitlabGroupId
	}
	return ""
}

func (x *Function) GetFrameworkType() string {
	if x != nil {
		return x.FrameworkType
	}
	return ""
}

func (x *Function) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Function) GetPipelineStatus() string {
	if x != nil {
		return x.PipelineStatus
	}
	return ""
}

func (x *Function) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Function) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Function) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Function) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Function) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Function) GetProvidedName() string {
	if x != nil {
		return x.ProvidedName
	}
	return ""
}

func (x *Function) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *Function) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Function) GetMaxScale() int32 {
	if x != nil {
		return x.MaxScale
	}
	return 0
}

func (x *Function) GetFormerMaxScale() int32 {
	if x != nil {
		return x.FormerMaxScale
	}
	return 0
}

type GetAllFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,5,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Type          []string               `protobuf:"bytes,6,rep,name=type,proto3" json:"type,omitempty"`
	FunctionId    string                 `protobuf:"bytes,7,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFunctionsRequest) Reset() {
	*x = GetAllFunctionsRequest{}
	mi := &file_pg_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFunctionsRequest) ProtoMessage() {}

func (x *GetAllFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFunctionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllFunctionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllFunctionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllFunctionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllFunctionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAllFunctionsRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *GetAllFunctionsRequest) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GetAllFunctionsRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

type GetAllFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*Function            `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFunctionsResponse) Reset() {
	*x = GetAllFunctionsResponse{}
	mi := &file_pg_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFunctionsResponse) ProtoMessage() {}

func (x *GetAllFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFunctionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllFunctionsResponse) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *GetAllFunctionsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FunctionPrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionPrimaryKey) Reset() {
	*x = FunctionPrimaryKey{}
	mi := &file_pg_function_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionPrimaryKey) ProtoMessage() {}

func (x *FunctionPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionPrimaryKey.ProtoReflect.Descriptor instead.
func (*FunctionPrimaryKey) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionPrimaryKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FunctionPrimaryKey) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FunctionPrimaryKey) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *FunctionPrimaryKey) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type UpdateManyUrlAndPassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManyUrlAndPassword) Reset() {
	*x = UpdateManyUrlAndPassword{}
	mi := &file_pg_function_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManyUrlAndPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyUrlAndPassword) ProtoMessage() {}

func (x *UpdateManyUrlAndPassword) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyUrlAndPassword.ProtoReflect.Descriptor instead.
func (*UpdateManyUrlAndPassword) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateManyUrlAndPassword) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateManyUrlAndPassword) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetListByRequestTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,5,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListByRequestTimeRequest) Reset() {
	*x = GetListByRequestTimeRequest{}
	mi := &file_pg_function_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListByRequestTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListByRequestTimeRequest) ProtoMessage() {}

func (x *GetListByRequestTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListByRequestTimeRequest.ProtoReflect.Descriptor instead.
func (*GetListByRequestTimeRequest) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{6}
}

func (x *GetListByRequestTimeRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetListByRequestTimeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListByRequestTimeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListByRequestTimeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetListByRequestTimeRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *GetListByRequestTimeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetCountByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Type          []string               `protobuf:"bytes,2,rep,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountByTypeRequest) Reset() {
	*x = GetCountByTypeRequest{}
	mi := &file_pg_function_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountByTypeRequest) ProtoMessage() {}

func (x *GetCountByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetCountByTypeRequest) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{7}
}

func (x *GetCountByTypeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetCountByTypeRequest) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

type GetCountByTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountByTypeResponse) Reset() {
	*x = GetCountByTypeResponse{}
	mi := &file_pg_function_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountByTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountByTypeResponse) ProtoMessage() {}

func (x *GetCountByTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pg_function_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountByTypeResponse.ProtoReflect.Descriptor instead.
func (*GetCountByTypeResponse) Descriptor() ([]byte, []int) {
	return file_pg_function_proto_rawDescGZIP(), []int{8}
}

func (x *GetCountByTypeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_pg_function_proto protoreflect.FileDescriptor

const file_pg_function_proto_rawDesc = "" +
	"\n" +
	"\x11pg_function.proto\x12\x1anew_object_builder_service\x1a\x1bgoogle/protobuf/empty.proto\"\xd7\x06\n" +
	"\x15CreateFunctionRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x05 \x01(\tR\tversionId\x12\x1b\n" +
	"\tcommit_id\x18\x06 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vcommit_guid\x18\a \x01(\tR\n" +
	"commitGuid\x12%\n" +
	"\x0eenvironment_id\x18\b \x01(\tR\renvironmentId\x12,\n" +
	"\x12function_folder_id\x18\t \x01(\tR\x10functionFolderId\x12\x10\n" +
	"\x03url\x18\n" +
	" \x01(\tR\x03url\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\x12\x17\n" +
	"\assh_url\x18\f \x01(\tR\x06sshUrl\x12\x12\n" +
	"\x04type\x18\r \x01(\tR\x04type\x12%\n" +
	"\x0eframework_type\x18\x10 \x01(\tR\rframeworkType\x12\x1b\n" +
	"\tgitlab_id\x18\x0e \x01(\tR\bgitlabId\x12&\n" +
	"\x0fgitlab_group_id\x18\x0f \x01(\tR\rgitlabGroupId\x12\x1d\n" +
	"\n" +
	"source_url\x18\x11 \x01(\tR\tsourceUrl\x12'\n" +
	"\x0fpipeline_status\x18\x12 \x01(\tR\x0epipelineStatus\x12\x16\n" +
	"\x06branch\x18\x13 \x01(\tR\x06branch\x12\x17\n" +
	"\arepo_id\x18\x14 \x01(\tR\x06repoId\x12#\n" +
	"\rerror_message\x18\x15 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bjob_name\x18\x16 \x01(\tR\ajobName\x12\x1a\n" +
	"\bresource\x18\x17 \x01(\tR\bresource\x12#\n" +
	"\rprovided_name\x18\x18 \x01(\tR\fprovidedName\x12\x1b\n" +
	"\tis_public\x18\x19 \x01(\bR\bisPublic\x12\x1b\n" +
	"\tmax_scale\x18\x1a \x01(\x05R\bmaxScale\x12(\n" +
	"\x10former_max_scale\x18\x1b \x01(\x05R\x0eformerMaxScale\"\xa0\x06\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12,\n" +
	"\x12function_folder_id\x18\a \x01(\tR\x10functionFolderId\x12%\n" +
	"\x0eenvironment_id\x18\b \x01(\tR\renvironmentId\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12\x17\n" +
	"\assh_url\x18\v \x01(\tR\x06sshUrl\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\x12\x1b\n" +
	"\tgitlab_id\x18\r \x01(\tR\bgitlabId\x12&\n" +
	"\x0fgitlab_group_id\x18\x0e \x01(\tR\rgitlabGroupId\x12%\n" +
	"\x0eframework_type\x18\x0f \x01(\tR\rframeworkType\x12\x1d\n" +
	"\n" +
	"source_url\x18\x10 \x01(\tR\tsourceUrl\x12'\n" +
	"\x0fpipeline_status\x18\x11 \x01(\tR\x0epipelineStatus\x12\x16\n" +
	"\x06branch\x18\x12 \x01(\tR\x06branch\x12\x17\n" +
	"\arepo_id\x18\x13 \x01(\tR\x06repoId\x12#\n" +
	"\rerror_message\x18\x14 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bjob_name\x18\x15 \x01(\tR\ajobName\x12\x1a\n" +
	"\bresource\x18\x16 \x01(\tR\bresource\x12#\n" +
	"\rprovided_name\x18\x17 \x01(\tR\fprovidedName\x12!\n" +
	"\frequest_type\x18\x18 \x01(\tR\vrequestType\x12\x1b\n" +
	"\tis_public\x18\x19 \x01(\bR\bisPublic\x12\x1b\n" +
	"\tmax_scale\x18\x1a \x01(\x05R\bmaxScale\x12(\n" +
	"\x10former_max_scale\x18\x1b \x01(\x05R\x0eformerMaxScale\"\xd9\x01\n" +
	"\x16GetAllFunctionsRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12%\n" +
	"\x0eenvironment_id\x18\x05 \x01(\tR\renvironmentId\x12\x12\n" +
	"\x04type\x18\x06 \x03(\tR\x04type\x12\x1f\n" +
	"\vfunction_id\x18\a \x01(\tR\n" +
	"functionId\"s\n" +
	"\x17GetAllFunctionsResponse\x12B\n" +
	"\tfunctions\x18\x01 \x03(\v2$.new_object_builder_service.FunctionR\tfunctions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8e\x01\n" +
	"\x12FunctionPrimaryKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tR\tsourceUrl\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\"K\n" +
	"\x18UpdateManyUrlAndPassword\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xbd\x01\n" +
	"\x1bGetListByRequestTimeRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12%\n" +
	"\x0eenvironment_id\x18\x05 \x01(\tR\renvironmentId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\"J\n" +
	"\x15GetCountByTypeRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04type\x18\x02 \x03(\tR\x04type\".\n" +
	"\x16GetCountByTypeResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xe0\x06\n" +
	"\x11FunctionServiceV2\x12c\n" +
	"\x06Create\x121.new_object_builder_service.CreateFunctionRequest\x1a$.new_object_builder_service.Function\"\x00\x12t\n" +
	"\aGetList\x122.new_object_builder_service.GetAllFunctionsRequest\x1a3.new_object_builder_service.GetAllFunctionsResponse\"\x00\x12c\n" +
	"\tGetSingle\x12..new_object_builder_service.FunctionPrimaryKey\x1a$.new_object_builder_service.Function\"\x00\x12H\n" +
	"\x06Update\x12$.new_object_builder_service.Function\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x06Delete\x12..new_object_builder_service.FunctionPrimaryKey\x1a\x16.google.protobuf.Empty\"\x00\x12\x86\x01\n" +
	"\x14GetListByRequestTime\x127.new_object_builder_service.GetListByRequestTimeRequest\x1a3.new_object_builder_service.GetAllFunctionsResponse\"\x00\x12i\n" +
	"\x17UpdateManyByRequestTime\x124.new_object_builder_service.UpdateManyUrlAndPassword\x1a\x16.google.protobuf.Empty\"\x00\x12y\n" +
	"\x0eGetCountByType\x121.new_object_builder_service.GetCountByTypeRequest\x1a2.new_object_builder_service.GetCountByTypeResponse\"\x00B%Z#genproto/new_object_builder_serviceb\x06proto3"

var (
	file_pg_function_proto_rawDescOnce sync.Once
	file_pg_function_proto_rawDescData []byte
)

func file_pg_function_proto_rawDescGZIP() []byte {
	file_pg_function_proto_rawDescOnce.Do(func() {
		file_pg_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pg_function_proto_rawDesc), len(file_pg_function_proto_rawDesc)))
	})
	return file_pg_function_proto_rawDescData
}

var file_pg_function_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pg_function_proto_goTypes = []any{
	(*CreateFunctionRequest)(nil),       // 0: new_object_builder_service.CreateFunctionRequest
	(*Function)(nil),                    // 1: new_object_builder_service.Function
	(*GetAllFunctionsRequest)(nil),      // 2: new_object_builder_service.GetAllFunctionsRequest
	(*GetAllFunctionsResponse)(nil),     // 3: new_object_builder_service.GetAllFunctionsResponse
	(*FunctionPrimaryKey)(nil),          // 4: new_object_builder_service.FunctionPrimaryKey
	(*UpdateManyUrlAndPassword)(nil),    // 5: new_object_builder_service.UpdateManyUrlAndPassword
	(*GetListByRequestTimeRequest)(nil), // 6: new_object_builder_service.GetListByRequestTimeRequest
	(*GetCountByTypeRequest)(nil),       // 7: new_object_builder_service.GetCountByTypeRequest
	(*GetCountByTypeResponse)(nil),      // 8: new_object_builder_service.GetCountByTypeResponse
	(*empty.Empty)(nil),                 // 9: google.protobuf.Empty
}
var file_pg_function_proto_depIdxs = []int32{
	1, // 0: new_object_builder_service.GetAllFunctionsResponse.functions:type_name -> new_object_builder_service.Function
	0, // 1: new_object_builder_service.FunctionServiceV2.Create:input_type -> new_object_builder_service.CreateFunctionRequest
	2, // 2: new_object_builder_service.FunctionServiceV2.GetList:input_type -> new_object_builder_service.GetAllFunctionsRequest
	4, // 3: new_object_builder_service.FunctionServiceV2.GetSingle:input_type -> new_object_builder_service.FunctionPrimaryKey
	1, // 4: new_object_builder_service.FunctionServiceV2.Update:input_type -> new_object_builder_service.Function
	4, // 5: new_object_builder_service.FunctionServiceV2.Delete:input_type -> new_object_builder_service.FunctionPrimaryKey
	6, // 6: new_object_builder_service.FunctionServiceV2.GetListByRequestTime:input_type -> new_object_builder_service.GetListByRequestTimeRequest
	5, // 7: new_object_builder_service.FunctionServiceV2.UpdateManyByRequestTime:input_type -> new_object_builder_service.UpdateManyUrlAndPassword
	7, // 8: new_object_builder_service.FunctionServiceV2.GetCountByType:input_type -> new_object_builder_service.GetCountByTypeRequest
	1, // 9: new_object_builder_service.FunctionServiceV2.Create:output_type -> new_object_builder_service.Function
	3, // 10: new_object_builder_service.FunctionServiceV2.GetList:output_type -> new_object_builder_service.GetAllFunctionsResponse
	1, // 11: new_object_builder_service.FunctionServiceV2.GetSingle:output_type -> new_object_builder_service.Function
	9, // 12: new_object_builder_service.FunctionServiceV2.Update:output_type -> google.protobuf.Empty
	9, // 13: new_object_builder_service.FunctionServiceV2.Delete:output_type -> google.protobuf.Empty
	3, // 14: new_object_builder_service.FunctionServiceV2.GetListByRequestTime:output_type -> new_object_builder_service.GetAllFunctionsResponse
	9, // 15: new_object_builder_service.FunctionServiceV2.UpdateManyByRequestTime:output_type -> google.protobuf.Empty
	8, // 16: new_object_builder_service.FunctionServiceV2.GetCountByType:output_type -> new_object_builder_service.GetCountByTypeResponse
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pg_function_proto_init() }
func file_pg_function_proto_init() {
	if File_pg_function_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pg_function_proto_rawDesc), len(file_pg_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pg_function_proto_goTypes,
		DependencyIndexes: file_pg_function_proto_depIdxs,
		MessageInfos:      file_pg_function_proto_msgTypes,
	}.Build()
	File_pg_function_proto = out.File
	file_pg_function_proto_goTypes = nil
	file_pg_function_proto_depIdxs = nil
}
