// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: cashbox_transaction.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CashboxTransactionClient is the client API for CashboxTransaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashboxTransactionClient interface {
	Create(ctx context.Context, in *CreateCashboxTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cashboxTransactionClient struct {
	cc grpc.ClientConnInterface
}

func NewCashboxTransactionClient(cc grpc.ClientConnInterface) CashboxTransactionClient {
	return &cashboxTransactionClient{cc}
}

func (c *cashboxTransactionClient) Create(ctx context.Context, in *CreateCashboxTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.CashboxTransaction/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashboxTransactionServer is the server API for CashboxTransaction service.
// All implementations must embed UnimplementedCashboxTransactionServer
// for forward compatibility
type CashboxTransactionServer interface {
	Create(context.Context, *CreateCashboxTransactionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCashboxTransactionServer()
}

// UnimplementedCashboxTransactionServer must be embedded to have forward compatible implementations.
type UnimplementedCashboxTransactionServer struct {
}

func (UnimplementedCashboxTransactionServer) Create(context.Context, *CreateCashboxTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCashboxTransactionServer) mustEmbedUnimplementedCashboxTransactionServer() {}

// UnsafeCashboxTransactionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashboxTransactionServer will
// result in compilation errors.
type UnsafeCashboxTransactionServer interface {
	mustEmbedUnimplementedCashboxTransactionServer()
}

func RegisterCashboxTransactionServer(s grpc.ServiceRegistrar, srv CashboxTransactionServer) {
	s.RegisterService(&CashboxTransaction_ServiceDesc, srv)
}

func _CashboxTransaction_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCashboxTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashboxTransactionServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.CashboxTransaction/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashboxTransactionServer).Create(ctx, req.(*CreateCashboxTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CashboxTransaction_ServiceDesc is the grpc.ServiceDesc for CashboxTransaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashboxTransaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.CashboxTransaction",
	HandlerType: (*CashboxTransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CashboxTransaction_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cashbox_transaction.proto",
}
