// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: custom_error_message.proto

package object_builder_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListForObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	LanguageId    string                 `protobuf:"bytes,2,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	TableSlug     string                 `protobuf:"bytes,4,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	TableId       string                 `protobuf:"bytes,5,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListForObjectRequest) Reset() {
	*x = GetListForObjectRequest{}
	mi := &file_custom_error_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListForObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListForObjectRequest) ProtoMessage() {}

func (x *GetListForObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListForObjectRequest.ProtoReflect.Descriptor instead.
func (*GetListForObjectRequest) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetListForObjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetListForObjectRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *GetListForObjectRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *GetListForObjectRequest) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *GetListForObjectRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type CustomErrorMessagePK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomErrorMessagePK) Reset() {
	*x = CustomErrorMessagePK{}
	mi := &file_custom_error_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomErrorMessagePK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomErrorMessagePK) ProtoMessage() {}

func (x *CustomErrorMessagePK) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomErrorMessagePK.ProtoReflect.Descriptor instead.
func (*CustomErrorMessagePK) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{1}
}

func (x *CustomErrorMessagePK) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomErrorMessagePK) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CreateCustomErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorId       string                 `protobuf:"bytes,4,opt,name=error_id,json=errorId,proto3" json:"error_id,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	LanguageId    string                 `protobuf:"bytes,6,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,7,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomErrorMessage) Reset() {
	*x = CreateCustomErrorMessage{}
	mi := &file_custom_error_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomErrorMessage) ProtoMessage() {}

func (x *CreateCustomErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomErrorMessage.ProtoReflect.Descriptor instead.
func (*CreateCustomErrorMessage) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomErrorMessage) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateCustomErrorMessage) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *CreateCustomErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCustomErrorMessage) GetErrorId() string {
	if x != nil {
		return x.ErrorId
	}
	return ""
}

func (x *CreateCustomErrorMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCustomErrorMessage) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *CreateCustomErrorMessage) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

type CustomErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorId       string                 `protobuf:"bytes,4,opt,name=error_id,json=errorId,proto3" json:"error_id,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	LanguageId    string                 `protobuf:"bytes,6,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,8,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomErrorMessage) Reset() {
	*x = CustomErrorMessage{}
	mi := &file_custom_error_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomErrorMessage) ProtoMessage() {}

func (x *CustomErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomErrorMessage.ProtoReflect.Descriptor instead.
func (*CustomErrorMessage) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{3}
}

func (x *CustomErrorMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomErrorMessage) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *CustomErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CustomErrorMessage) GetErrorId() string {
	if x != nil {
		return x.ErrorId
	}
	return ""
}

func (x *CustomErrorMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CustomErrorMessage) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *CustomErrorMessage) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CustomErrorMessage) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

type VariableForCustomErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableForCustomErrorMessage) Reset() {
	*x = VariableForCustomErrorMessage{}
	mi := &file_custom_error_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableForCustomErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableForCustomErrorMessage) ProtoMessage() {}

func (x *VariableForCustomErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableForCustomErrorMessage.ProtoReflect.Descriptor instead.
func (*VariableForCustomErrorMessage) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{4}
}

func (x *VariableForCustomErrorMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VariableForCustomErrorMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetCustomErrorMessageListResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CustomErrorMessages []*CustomErrorMessage  `protobuf:"bytes,1,rep,name=custom_error_messages,json=customErrorMessages,proto3" json:"custom_error_messages,omitempty"`
	Count               int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCustomErrorMessageListResponse) Reset() {
	*x = GetCustomErrorMessageListResponse{}
	mi := &file_custom_error_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomErrorMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomErrorMessageListResponse) ProtoMessage() {}

func (x *GetCustomErrorMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomErrorMessageListResponse.ProtoReflect.Descriptor instead.
func (*GetCustomErrorMessageListResponse) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomErrorMessageListResponse) GetCustomErrorMessages() []*CustomErrorMessage {
	if x != nil {
		return x.CustomErrorMessages
	}
	return nil
}

func (x *GetCustomErrorMessageListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCustomErrorMessageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableSlug     string                 `protobuf:"bytes,1,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomErrorMessageListRequest) Reset() {
	*x = GetCustomErrorMessageListRequest{}
	mi := &file_custom_error_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomErrorMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomErrorMessageListRequest) ProtoMessage() {}

func (x *GetCustomErrorMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_custom_error_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomErrorMessageListRequest.ProtoReflect.Descriptor instead.
func (*GetCustomErrorMessageListRequest) Descriptor() ([]byte, []int) {
	return file_custom_error_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomErrorMessageListRequest) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *GetCustomErrorMessageListRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetCustomErrorMessageListRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

var File_custom_error_message_proto protoreflect.FileDescriptor

const file_custom_error_message_proto_rawDesc = "" +
	"\n" +
	"\x1acustom_error_message.proto\x12\x16object_builder_service\x1a\x1bgoogle/protobuf/empty.proto\"\xb4\x01\n" +
	"\x17GetListForObjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vlanguage_id\x18\x02 \x01(\tR\n" +
	"languageId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x04 \x01(\tR\ttableSlug\x12\x19\n" +
	"\btable_id\x18\x05 \x01(\tR\atableId\"E\n" +
	"\x14CustomErrorMessagePK\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xdf\x01\n" +
	"\x18CreateCustomErrorMessage\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\berror_id\x18\x04 \x01(\tR\aerrorId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x1f\n" +
	"\vlanguage_id\x18\x06 \x01(\tR\n" +
	"languageId\x12\x1f\n" +
	"\vaction_type\x18\a \x01(\tR\n" +
	"actionType\"\xe9\x01\n" +
	"\x12CustomErrorMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\berror_id\x18\x04 \x01(\tR\aerrorId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x1f\n" +
	"\vlanguage_id\x18\x06 \x01(\tR\n" +
	"languageId\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x1f\n" +
	"\vaction_type\x18\b \x01(\tR\n" +
	"actionType\"G\n" +
	"\x1dVariableForCustomErrorMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x99\x01\n" +
	"!GetCustomErrorMessageListResponse\x12^\n" +
	"\x15custom_error_messages\x18\x01 \x03(\v2*.object_builder_service.CustomErrorMessageR\x13customErrorMessages\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"{\n" +
	" GetCustomErrorMessageListRequest\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x01 \x01(\tR\ttableSlug\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId2\x94\x05\n" +
	"\x19CustomErrorMessageService\x12h\n" +
	"\x06Create\x120.object_builder_service.CreateCustomErrorMessage\x1a*.object_builder_service.CustomErrorMessage\"\x00\x12\x80\x01\n" +
	"\aGetList\x128.object_builder_service.GetCustomErrorMessageListRequest\x1a9.object_builder_service.GetCustomErrorMessageListResponse\"\x00\x12\x80\x01\n" +
	"\x10GetListForObject\x12/.object_builder_service.GetListForObjectRequest\x1a9.object_builder_service.GetCustomErrorMessageListResponse\"\x00\x12N\n" +
	"\x06Update\x12*.object_builder_service.CustomErrorMessage\x1a\x16.google.protobuf.Empty\"\x00\x12e\n" +
	"\aGetById\x12,.object_builder_service.CustomErrorMessagePK\x1a*.object_builder_service.CustomErrorMessage\"\x00\x12P\n" +
	"\x06Delete\x12,.object_builder_service.CustomErrorMessagePK\x1a\x16.google.protobuf.Empty\"\x00B!Z\x1fgenproto/object_builder_serviceb\x06proto3"

var (
	file_custom_error_message_proto_rawDescOnce sync.Once
	file_custom_error_message_proto_rawDescData []byte
)

func file_custom_error_message_proto_rawDescGZIP() []byte {
	file_custom_error_message_proto_rawDescOnce.Do(func() {
		file_custom_error_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_custom_error_message_proto_rawDesc), len(file_custom_error_message_proto_rawDesc)))
	})
	return file_custom_error_message_proto_rawDescData
}

var file_custom_error_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_custom_error_message_proto_goTypes = []any{
	(*GetListForObjectRequest)(nil),           // 0: object_builder_service.GetListForObjectRequest
	(*CustomErrorMessagePK)(nil),              // 1: object_builder_service.CustomErrorMessagePK
	(*CreateCustomErrorMessage)(nil),          // 2: object_builder_service.CreateCustomErrorMessage
	(*CustomErrorMessage)(nil),                // 3: object_builder_service.CustomErrorMessage
	(*VariableForCustomErrorMessage)(nil),     // 4: object_builder_service.VariableForCustomErrorMessage
	(*GetCustomErrorMessageListResponse)(nil), // 5: object_builder_service.GetCustomErrorMessageListResponse
	(*GetCustomErrorMessageListRequest)(nil),  // 6: object_builder_service.GetCustomErrorMessageListRequest
	(*empty.Empty)(nil),                       // 7: google.protobuf.Empty
}
var file_custom_error_message_proto_depIdxs = []int32{
	3, // 0: object_builder_service.GetCustomErrorMessageListResponse.custom_error_messages:type_name -> object_builder_service.CustomErrorMessage
	2, // 1: object_builder_service.CustomErrorMessageService.Create:input_type -> object_builder_service.CreateCustomErrorMessage
	6, // 2: object_builder_service.CustomErrorMessageService.GetList:input_type -> object_builder_service.GetCustomErrorMessageListRequest
	0, // 3: object_builder_service.CustomErrorMessageService.GetListForObject:input_type -> object_builder_service.GetListForObjectRequest
	3, // 4: object_builder_service.CustomErrorMessageService.Update:input_type -> object_builder_service.CustomErrorMessage
	1, // 5: object_builder_service.CustomErrorMessageService.GetById:input_type -> object_builder_service.CustomErrorMessagePK
	1, // 6: object_builder_service.CustomErrorMessageService.Delete:input_type -> object_builder_service.CustomErrorMessagePK
	3, // 7: object_builder_service.CustomErrorMessageService.Create:output_type -> object_builder_service.CustomErrorMessage
	5, // 8: object_builder_service.CustomErrorMessageService.GetList:output_type -> object_builder_service.GetCustomErrorMessageListResponse
	5, // 9: object_builder_service.CustomErrorMessageService.GetListForObject:output_type -> object_builder_service.GetCustomErrorMessageListResponse
	7, // 10: object_builder_service.CustomErrorMessageService.Update:output_type -> google.protobuf.Empty
	3, // 11: object_builder_service.CustomErrorMessageService.GetById:output_type -> object_builder_service.CustomErrorMessage
	7, // 12: object_builder_service.CustomErrorMessageService.Delete:output_type -> google.protobuf.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_custom_error_message_proto_init() }
func file_custom_error_message_proto_init() {
	if File_custom_error_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_custom_error_message_proto_rawDesc), len(file_custom_error_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_custom_error_message_proto_goTypes,
		DependencyIndexes: file_custom_error_message_proto_depIdxs,
		MessageInfos:      file_custom_error_message_proto_msgTypes,
	}.Build()
	File_custom_error_message_proto = out.File
	file_custom_error_message_proto_goTypes = nil
	file_custom_error_message_proto_depIdxs = nil
}
