// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: event_logs.proto

package object_builder_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventLogsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableSlug     string                 `protobuf:"bytes,1,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventLogsListRequest) Reset() {
	*x = GetEventLogsListRequest{}
	mi := &file_event_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventLogsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventLogsListRequest) ProtoMessage() {}

func (x *GetEventLogsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventLogsListRequest.ProtoReflect.Descriptor instead.
func (*GetEventLogsListRequest) Descriptor() ([]byte, []int) {
	return file_event_logs_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventLogsListRequest) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *GetEventLogsListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetEventLogsListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetEventLogsListRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetEventLogById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventLogById) Reset() {
	*x = GetEventLogById{}
	mi := &file_event_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventLogById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventLogById) ProtoMessage() {}

func (x *GetEventLogById) ProtoReflect() protoreflect.Message {
	mi := &file_event_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventLogById.ProtoReflect.Descriptor instead.
func (*GetEventLogById) Descriptor() ([]byte, []int) {
	return file_event_logs_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventLogById) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEventLogById) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type EventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	TableSlug     string                 `protobuf:"bytes,4,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	EffectedTable string                 `protobuf:"bytes,5,opt,name=effected_table,json=effectedTable,proto3" json:"effected_table,omitempty"`
	ProjectId     string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	mi := &file_event_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_event_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_event_logs_proto_rawDescGZIP(), []int{2}
}

func (x *EventLog) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *EventLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventLog) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EventLog) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *EventLog) GetEffectedTable() string {
	if x != nil {
		return x.EffectedTable
	}
	return ""
}

func (x *EventLog) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetEventLogListsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventLogs     []*EventLog            `protobuf:"bytes,1,rep,name=event_logs,json=eventLogs,proto3" json:"event_logs,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventLogListsResponse) Reset() {
	*x = GetEventLogListsResponse{}
	mi := &file_event_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventLogListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventLogListsResponse) ProtoMessage() {}

func (x *GetEventLogListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventLogListsResponse.ProtoReflect.Descriptor instead.
func (*GetEventLogListsResponse) Descriptor() ([]byte, []int) {
	return file_event_logs_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventLogListsResponse) GetEventLogs() []*EventLog {
	if x != nil {
		return x.EventLogs
	}
	return nil
}

func (x *GetEventLogListsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_event_logs_proto protoreflect.FileDescriptor

const file_event_logs_proto_rawDesc = "" +
	"\n" +
	"\x10event_logs.proto\x12\x16object_builder_service\"\x85\x01\n" +
	"\x17GetEventLogsListRequest\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x01 \x01(\tR\ttableSlug\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"@\n" +
	"\x0fGetEventLogById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xa7\x01\n" +
	"\bEventLog\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x04 \x01(\tR\ttableSlug\x12%\n" +
	"\x0eeffected_table\x18\x05 \x01(\tR\reffectedTable\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\"q\n" +
	"\x18GetEventLogListsResponse\x12?\n" +
	"\n" +
	"event_logs\x18\x01 \x03(\v2 .object_builder_service.EventLogR\teventLogs\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xdc\x01\n" +
	"\x10EventLogsService\x12n\n" +
	"\aGetList\x12/.object_builder_service.GetEventLogsListRequest\x1a0.object_builder_service.GetEventLogListsResponse\"\x00\x12X\n" +
	"\tGetSingle\x12'.object_builder_service.GetEventLogById\x1a .object_builder_service.EventLog\"\x00B!Z\x1fgenproto/object_builder_serviceb\x06proto3"

var (
	file_event_logs_proto_rawDescOnce sync.Once
	file_event_logs_proto_rawDescData []byte
)

func file_event_logs_proto_rawDescGZIP() []byte {
	file_event_logs_proto_rawDescOnce.Do(func() {
		file_event_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_logs_proto_rawDesc), len(file_event_logs_proto_rawDesc)))
	})
	return file_event_logs_proto_rawDescData
}

var file_event_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_logs_proto_goTypes = []any{
	(*GetEventLogsListRequest)(nil),  // 0: object_builder_service.GetEventLogsListRequest
	(*GetEventLogById)(nil),          // 1: object_builder_service.GetEventLogById
	(*EventLog)(nil),                 // 2: object_builder_service.EventLog
	(*GetEventLogListsResponse)(nil), // 3: object_builder_service.GetEventLogListsResponse
}
var file_event_logs_proto_depIdxs = []int32{
	2, // 0: object_builder_service.GetEventLogListsResponse.event_logs:type_name -> object_builder_service.EventLog
	0, // 1: object_builder_service.EventLogsService.GetList:input_type -> object_builder_service.GetEventLogsListRequest
	1, // 2: object_builder_service.EventLogsService.GetSingle:input_type -> object_builder_service.GetEventLogById
	3, // 3: object_builder_service.EventLogsService.GetList:output_type -> object_builder_service.GetEventLogListsResponse
	2, // 4: object_builder_service.EventLogsService.GetSingle:output_type -> object_builder_service.EventLog
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_logs_proto_init() }
func file_event_logs_proto_init() {
	if File_event_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_logs_proto_rawDesc), len(file_event_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_logs_proto_goTypes,
		DependencyIndexes: file_event_logs_proto_depIdxs,
		MessageInfos:      file_event_logs_proto_msgTypes,
	}.Build()
	File_event_logs_proto = out.File
	file_event_logs_proto_goTypes = nil
	file_event_logs_proto_depIdxs = nil
}
