// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: excel.proto

package object_builder_service

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExcelReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelReadRequest) Reset() {
	*x = ExcelReadRequest{}
	mi := &file_excel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelReadRequest) ProtoMessage() {}

func (x *ExcelReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelReadRequest.ProtoReflect.Descriptor instead.
func (*ExcelReadRequest) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{0}
}

func (x *ExcelReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExcelReadRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExcelReadRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ExcelToDbRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TableSlug     string                 `protobuf:"bytes,2,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelToDbRequest) Reset() {
	*x = ExcelToDbRequest{}
	mi := &file_excel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelToDbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelToDbRequest) ProtoMessage() {}

func (x *ExcelToDbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelToDbRequest.ProtoReflect.Descriptor instead.
func (*ExcelToDbRequest) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{1}
}

func (x *ExcelToDbRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExcelToDbRequest) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *ExcelToDbRequest) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExcelToDbRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExcelToDbRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ExcelToDbResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelToDbResponse) Reset() {
	*x = ExcelToDbResponse{}
	mi := &file_excel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelToDbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelToDbResponse) ProtoMessage() {}

func (x *ExcelToDbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelToDbResponse.ProtoReflect.Descriptor instead.
func (*ExcelToDbResponse) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{2}
}

type ExcelReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []string               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExcelReadResponse) Reset() {
	*x = ExcelReadResponse{}
	mi := &file_excel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExcelReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelReadResponse) ProtoMessage() {}

func (x *ExcelReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelReadResponse.ProtoReflect.Descriptor instead.
func (*ExcelReadResponse) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{3}
}

func (x *ExcelReadResponse) GetRows() []string {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExcelReadResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        []string               `protobuf:"bytes,1,rep,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_excel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetColumn() []string {
	if x != nil {
		return x.Column
	}
	return nil
}

var File_excel_proto protoreflect.FileDescriptor

const file_excel_proto_rawDesc = "" +
	"\n" +
	"\vexcel.proto\x12\x16object_builder_service\x1a\x1cgoogle/protobuf/struct.proto\"U\n" +
	"\x10ExcelReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xa1\x01\n" +
	"\x10ExcelToDbRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x02 \x01(\tR\ttableSlug\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\x13\n" +
	"\x11ExcelToDbResponse\";\n" +
	"\x11ExcelReadResponse\x12\x12\n" +
	"\x04rows\x18\x01 \x03(\tR\x04rows\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06column\x18\x01 \x03(\tR\x06column2\xd6\x01\n" +
	"\fExcelService\x12b\n" +
	"\tExcelRead\x12(.object_builder_service.ExcelReadRequest\x1a).object_builder_service.ExcelReadResponse\"\x00\x12b\n" +
	"\tExcelToDb\x12(.object_builder_service.ExcelToDbRequest\x1a).object_builder_service.ExcelToDbResponse\"\x00B!Z\x1fgenproto/object_builder_serviceb\x06proto3"

var (
	file_excel_proto_rawDescOnce sync.Once
	file_excel_proto_rawDescData []byte
)

func file_excel_proto_rawDescGZIP() []byte {
	file_excel_proto_rawDescOnce.Do(func() {
		file_excel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_excel_proto_rawDesc), len(file_excel_proto_rawDesc)))
	})
	return file_excel_proto_rawDescData
}

var file_excel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_excel_proto_goTypes = []any{
	(*ExcelReadRequest)(nil),  // 0: object_builder_service.ExcelReadRequest
	(*ExcelToDbRequest)(nil),  // 1: object_builder_service.ExcelToDbRequest
	(*ExcelToDbResponse)(nil), // 2: object_builder_service.ExcelToDbResponse
	(*ExcelReadResponse)(nil), // 3: object_builder_service.ExcelReadResponse
	(*Row)(nil),               // 4: object_builder_service.Row
	(*_struct.Struct)(nil),    // 5: google.protobuf.Struct
}
var file_excel_proto_depIdxs = []int32{
	5, // 0: object_builder_service.ExcelToDbRequest.data:type_name -> google.protobuf.Struct
	0, // 1: object_builder_service.ExcelService.ExcelRead:input_type -> object_builder_service.ExcelReadRequest
	1, // 2: object_builder_service.ExcelService.ExcelToDb:input_type -> object_builder_service.ExcelToDbRequest
	3, // 3: object_builder_service.ExcelService.ExcelRead:output_type -> object_builder_service.ExcelReadResponse
	2, // 4: object_builder_service.ExcelService.ExcelToDb:output_type -> object_builder_service.ExcelToDbResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_excel_proto_init() }
func file_excel_proto_init() {
	if File_excel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_excel_proto_rawDesc), len(file_excel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_excel_proto_goTypes,
		DependencyIndexes: file_excel_proto_depIdxs,
		MessageInfos:      file_excel_proto_msgTypes,
	}.Build()
	File_excel_proto = out.File
	file_excel_proto_goTypes = nil
	file_excel_proto_depIdxs = nil
}
