// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: field.proto

package object_builder_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFieldRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Default             string                 `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Index               string                 `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	Label               string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Slug                string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	TableId             string                 `protobuf:"bytes,6,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Attributes          *_struct.Struct        `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Id                  string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	IsVisible           bool                   `protobuf:"varint,9,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	AutofillTable       string                 `protobuf:"bytes,10,opt,name=autofill_table,json=autofillTable,proto3" json:"autofill_table,omitempty"`
	AutofillField       string                 `protobuf:"bytes,11,opt,name=autofill_field,json=autofillField,proto3" json:"autofill_field,omitempty"`
	Unique              bool                   `protobuf:"varint,12,opt,name=unique,proto3" json:"unique,omitempty"`
	Automatic           bool                   `protobuf:"varint,13,opt,name=automatic,proto3" json:"automatic,omitempty"`
	ProjectId           string                 `protobuf:"bytes,14,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitId            string                 `protobuf:"bytes,15,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	VersionId           string                 `protobuf:"bytes,16,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	RelationField       string                 `protobuf:"bytes,17,opt,name=relation_field,json=relationField,proto3" json:"relation_field,omitempty"`
	ShowLabel           bool                   `protobuf:"varint,18,opt,name=show_label,json=showLabel,proto3" json:"show_label,omitempty"`
	EnableMultilanguage bool                   `protobuf:"varint,19,opt,name=enable_multilanguage,json=enableMultilanguage,proto3" json:"enable_multilanguage,omitempty"`
	HideMultilanguage   bool                   `protobuf:"varint,20,opt,name=hide_multilanguage,json=hideMultilanguage,proto3" json:"hide_multilanguage,omitempty"`
	MinioFolder         string                 `protobuf:"bytes,21,opt,name=minio_folder,json=minioFolder,proto3" json:"minio_folder,omitempty"`
	EnvId               string                 `protobuf:"bytes,22,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	IsAlt               bool                   `protobuf:"varint,23,opt,name=is_alt,json=isAlt,proto3" json:"is_alt,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateFieldRequest) Reset() {
	*x = CreateFieldRequest{}
	mi := &file_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFieldRequest) ProtoMessage() {}

func (x *CreateFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFieldRequest.ProtoReflect.Descriptor instead.
func (*CreateFieldRequest) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFieldRequest) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *CreateFieldRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFieldRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *CreateFieldRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateFieldRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateFieldRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *CreateFieldRequest) GetAttributes() *_struct.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateFieldRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateFieldRequest) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *CreateFieldRequest) GetAutofillTable() string {
	if x != nil {
		return x.AutofillTable
	}
	return ""
}

func (x *CreateFieldRequest) GetAutofillField() string {
	if x != nil {
		return x.AutofillField
	}
	return ""
}

func (x *CreateFieldRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *CreateFieldRequest) GetAutomatic() bool {
	if x != nil {
		return x.Automatic
	}
	return false
}

func (x *CreateFieldRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateFieldRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CreateFieldRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *CreateFieldRequest) GetRelationField() string {
	if x != nil {
		return x.RelationField
	}
	return ""
}

func (x *CreateFieldRequest) GetShowLabel() bool {
	if x != nil {
		return x.ShowLabel
	}
	return false
}

func (x *CreateFieldRequest) GetEnableMultilanguage() bool {
	if x != nil {
		return x.EnableMultilanguage
	}
	return false
}

func (x *CreateFieldRequest) GetHideMultilanguage() bool {
	if x != nil {
		return x.HideMultilanguage
	}
	return false
}

func (x *CreateFieldRequest) GetMinioFolder() string {
	if x != nil {
		return x.MinioFolder
	}
	return ""
}

func (x *CreateFieldRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *CreateFieldRequest) GetIsAlt() bool {
	if x != nil {
		return x.IsAlt
	}
	return false
}

type CreateFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Default       string                 `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Index         string                 `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Slug          string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Required      bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	Attributes    *_struct.Struct        `protobuf:"bytes,8,opt,name=attributes,proto3" json:"attributes,omitempty"`
	IsVisible     bool                   `protobuf:"varint,9,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	Unique        bool                   `protobuf:"varint,10,opt,name=unique,proto3" json:"unique,omitempty"`
	Automatic     bool                   `protobuf:"varint,11,opt,name=automatic,proto3" json:"automatic,omitempty"`
	ProjectId     string                 `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitId      string                 `protobuf:"bytes,13,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	MinioFolder   string                 `protobuf:"bytes,14,opt,name=minio_folder,json=minioFolder,proto3" json:"minio_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFieldsRequest) Reset() {
	*x = CreateFieldsRequest{}
	mi := &file_field_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFieldsRequest) ProtoMessage() {}

func (x *CreateFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFieldsRequest.ProtoReflect.Descriptor instead.
func (*CreateFieldsRequest) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFieldsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateFieldsRequest) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *CreateFieldsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFieldsRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *CreateFieldsRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateFieldsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateFieldsRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CreateFieldsRequest) GetAttributes() *_struct.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateFieldsRequest) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *CreateFieldsRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *CreateFieldsRequest) GetAutomatic() bool {
	if x != nil {
		return x.Automatic
	}
	return false
}

func (x *CreateFieldsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateFieldsRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CreateFieldsRequest) GetMinioFolder() string {
	if x != nil {
		return x.MinioFolder
	}
	return ""
}

type Field struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Default             string                 `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Index               string                 `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	Label               string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Slug                string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	TableId             string                 `protobuf:"bytes,7,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Required            bool                   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	Attributes          *_struct.Struct        `protobuf:"bytes,9,opt,name=attributes,proto3" json:"attributes,omitempty"`
	IsVisible           bool                   `protobuf:"varint,10,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	AutofillField       string                 `protobuf:"bytes,11,opt,name=autofill_field,json=autofillField,proto3" json:"autofill_field,omitempty"`
	AutofillTable       string                 `protobuf:"bytes,12,opt,name=autofill_table,json=autofillTable,proto3" json:"autofill_table,omitempty"`
	RelationId          string                 `protobuf:"bytes,13,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	Unique              bool                   `protobuf:"varint,14,opt,name=unique,proto3" json:"unique,omitempty"`
	Automatic           bool                   `protobuf:"varint,15,opt,name=automatic,proto3" json:"automatic,omitempty"`
	ProjectId           string                 `protobuf:"bytes,16,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitId            string                 `protobuf:"bytes,17,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	VersionId           string                 `protobuf:"bytes,18,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	IsSystem            bool                   `protobuf:"varint,19,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	RelationField       string                 `protobuf:"bytes,20,opt,name=relation_field,json=relationField,proto3" json:"relation_field,omitempty"`
	ShowLabel           bool                   `protobuf:"varint,21,opt,name=show_label,json=showLabel,proto3" json:"show_label,omitempty"`
	EnableMultilanguage bool                   `protobuf:"varint,22,opt,name=enable_multilanguage,json=enableMultilanguage,proto3" json:"enable_multilanguage,omitempty"`
	HideMultilanguage   bool                   `protobuf:"varint,23,opt,name=hide_multilanguage,json=hideMultilanguage,proto3" json:"hide_multilanguage,omitempty"`
	MinioFolder         string                 `protobuf:"bytes,24,opt,name=minio_folder,json=minioFolder,proto3" json:"minio_folder,omitempty"`
	EnvId               string                 `protobuf:"bytes,25,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	IsSearch            bool                   `protobuf:"varint,26,opt,name=is_search,json=isSearch,proto3" json:"is_search,omitempty"`
	IsAlt               bool                   `protobuf:"varint,27,opt,name=is_alt,json=isAlt,proto3" json:"is_alt,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_field_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Field) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Field) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Field) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Field) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Field) GetAttributes() *_struct.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Field) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *Field) GetAutofillField() string {
	if x != nil {
		return x.AutofillField
	}
	return ""
}

func (x *Field) GetAutofillTable() string {
	if x != nil {
		return x.AutofillTable
	}
	return ""
}

func (x *Field) GetRelationId() string {
	if x != nil {
		return x.RelationId
	}
	return ""
}

func (x *Field) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Field) GetAutomatic() bool {
	if x != nil {
		return x.Automatic
	}
	return false
}

func (x *Field) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Field) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Field) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *Field) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *Field) GetRelationField() string {
	if x != nil {
		return x.RelationField
	}
	return ""
}

func (x *Field) GetShowLabel() bool {
	if x != nil {
		return x.ShowLabel
	}
	return false
}

func (x *Field) GetEnableMultilanguage() bool {
	if x != nil {
		return x.EnableMultilanguage
	}
	return false
}

func (x *Field) GetHideMultilanguage() bool {
	if x != nil {
		return x.HideMultilanguage
	}
	return false
}

func (x *Field) GetMinioFolder() string {
	if x != nil {
		return x.MinioFolder
	}
	return ""
}

func (x *Field) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *Field) GetIsSearch() bool {
	if x != nil {
		return x.IsSearch
	}
	return false
}

func (x *Field) GetIsAlt() bool {
	if x != nil {
		return x.IsAlt
	}
	return false
}

type SearchUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsSearch      bool                   `protobuf:"varint,2,opt,name=is_search,json=isSearch,proto3" json:"is_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUpdate) Reset() {
	*x = SearchUpdate{}
	mi := &file_field_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUpdate) ProtoMessage() {}

func (x *SearchUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUpdate.ProtoReflect.Descriptor instead.
func (*SearchUpdate) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchUpdate) GetIsSearch() bool {
	if x != nil {
		return x.IsSearch
	}
	return false
}

type SearchUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TableSlug     string                 `protobuf:"bytes,2,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	Fields        []*SearchUpdate        `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUpdateRequest) Reset() {
	*x = SearchUpdateRequest{}
	mi := &file_field_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUpdateRequest) ProtoMessage() {}

func (x *SearchUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUpdateRequest.ProtoReflect.Descriptor instead.
func (*SearchUpdateRequest) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUpdateRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SearchUpdateRequest) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *SearchUpdateRequest) GetFields() []*SearchUpdate {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetAllFieldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllFieldsResponse) Reset() {
	*x = GetAllFieldsResponse{}
	mi := &file_field_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFieldsResponse) ProtoMessage() {}

func (x *GetAllFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetAllFieldsResponse) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllFieldsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *GetAllFieldsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAllFieldsResponse) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllFieldsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TableId          string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Search           string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	TableSlug        string                 `protobuf:"bytes,5,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	WithManyRelation bool                   `protobuf:"varint,6,opt,name=with_many_relation,json=withManyRelation,proto3" json:"with_many_relation,omitempty"`
	WithOneRelation  bool                   `protobuf:"varint,7,opt,name=with_one_relation,json=withOneRelation,proto3" json:"with_one_relation,omitempty"`
	RoleId           string                 `protobuf:"bytes,8,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ProjectId        string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	VersionId        string                 `protobuf:"bytes,10,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllFieldsRequest) Reset() {
	*x = GetAllFieldsRequest{}
	mi := &file_field_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFieldsRequest) ProtoMessage() {}

func (x *GetAllFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFieldsRequest) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllFieldsRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *GetAllFieldsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllFieldsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllFieldsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllFieldsRequest) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *GetAllFieldsRequest) GetWithManyRelation() bool {
	if x != nil {
		return x.WithManyRelation
	}
	return false
}

func (x *GetAllFieldsRequest) GetWithOneRelation() bool {
	if x != nil {
		return x.WithOneRelation
	}
	return false
}

func (x *GetAllFieldsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *GetAllFieldsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAllFieldsRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type FieldPrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvId         string                 `protobuf:"bytes,3,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPrimaryKey) Reset() {
	*x = FieldPrimaryKey{}
	mi := &file_field_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPrimaryKey) ProtoMessage() {}

func (x *FieldPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPrimaryKey.ProtoReflect.Descriptor instead.
func (*FieldPrimaryKey) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{7}
}

func (x *FieldPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FieldPrimaryKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FieldPrimaryKey) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type GetAllFieldsForItemsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Collection       string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	RoleId           string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ProjectId        string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	VersionId        string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	LanguageSettings string                 `protobuf:"bytes,5,opt,name=language_settings,json=languageSettings,proto3" json:"language_settings,omitempty"`
	WithRelations    bool                   `protobuf:"varint,6,opt,name=with_relations,json=withRelations,proto3" json:"with_relations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllFieldsForItemsRequest) Reset() {
	*x = GetAllFieldsForItemsRequest{}
	mi := &file_field_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllFieldsForItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFieldsForItemsRequest) ProtoMessage() {}

func (x *GetAllFieldsForItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFieldsForItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFieldsForItemsRequest) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllFieldsForItemsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetAllFieldsForItemsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *GetAllFieldsForItemsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAllFieldsForItemsRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetAllFieldsForItemsRequest) GetLanguageSettings() string {
	if x != nil {
		return x.LanguageSettings
	}
	return ""
}

func (x *GetAllFieldsForItemsRequest) GetWithRelations() bool {
	if x != nil {
		return x.WithRelations
	}
	return false
}

type AllFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllFields) Reset() {
	*x = AllFields{}
	mi := &file_field_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllFields) ProtoMessage() {}

func (x *AllFields) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllFields.ProtoReflect.Descriptor instead.
func (*AllFields) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{9}
}

func (x *AllFields) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AllFields) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAllByLabelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FieldLabel    string                 `protobuf:"bytes,2,opt,name=field_label,json=fieldLabel,proto3" json:"field_label,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByLabelReq) Reset() {
	*x = GetAllByLabelReq{}
	mi := &file_field_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByLabelReq) ProtoMessage() {}

func (x *GetAllByLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByLabelReq.ProtoReflect.Descriptor instead.
func (*GetAllByLabelReq) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllByLabelReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAllByLabelReq) GetFieldLabel() string {
	if x != nil {
		return x.FieldLabel
	}
	return ""
}

func (x *GetAllByLabelReq) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type GetIdsByLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdsByLabelResponse) Reset() {
	*x = GetIdsByLabelResponse{}
	mi := &file_field_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdsByLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdsByLabelResponse) ProtoMessage() {}

func (x *GetIdsByLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdsByLabelResponse.ProtoReflect.Descriptor instead.
func (*GetIdsByLabelResponse) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{11}
}

func (x *GetIdsByLabelResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetIdsByLabelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FieldLabel    []string               `protobuf:"bytes,2,rep,name=field_label,json=fieldLabel,proto3" json:"field_label,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdsByLabelReq) Reset() {
	*x = GetIdsByLabelReq{}
	mi := &file_field_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdsByLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdsByLabelReq) ProtoMessage() {}

func (x *GetIdsByLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdsByLabelReq.ProtoReflect.Descriptor instead.
func (*GetIdsByLabelReq) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{12}
}

func (x *GetIdsByLabelReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetIdsByLabelReq) GetFieldLabel() []string {
	if x != nil {
		return x.FieldLabel
	}
	return nil
}

func (x *GetIdsByLabelReq) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

var File_field_proto protoreflect.FileDescriptor

const file_field_proto_rawDesc = "" +
	"\n" +
	"\vfield.proto\x12\x16object_builder_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xdd\x05\n" +
	"\x12CreateFieldRequest\x12\x18\n" +
	"\adefault\x18\x01 \x01(\tR\adefault\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05index\x18\x03 \x01(\tR\x05index\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x19\n" +
	"\btable_id\x18\x06 \x01(\tR\atableId\x127\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"is_visible\x18\t \x01(\bR\tisVisible\x12%\n" +
	"\x0eautofill_table\x18\n" +
	" \x01(\tR\rautofillTable\x12%\n" +
	"\x0eautofill_field\x18\v \x01(\tR\rautofillField\x12\x16\n" +
	"\x06unique\x18\f \x01(\bR\x06unique\x12\x1c\n" +
	"\tautomatic\x18\r \x01(\bR\tautomatic\x12\x1d\n" +
	"\n" +
	"project_id\x18\x0e \x01(\tR\tprojectId\x12\x1b\n" +
	"\tcommit_id\x18\x0f \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x10 \x01(\tR\tversionId\x12%\n" +
	"\x0erelation_field\x18\x11 \x01(\tR\rrelationField\x12\x1d\n" +
	"\n" +
	"show_label\x18\x12 \x01(\bR\tshowLabel\x121\n" +
	"\x14enable_multilanguage\x18\x13 \x01(\bR\x13enableMultilanguage\x12-\n" +
	"\x12hide_multilanguage\x18\x14 \x01(\bR\x11hideMultilanguage\x12!\n" +
	"\fminio_folder\x18\x15 \x01(\tR\vminioFolder\x12\x15\n" +
	"\x06env_id\x18\x16 \x01(\tR\x05envId\x12\x15\n" +
	"\x06is_alt\x18\x17 \x01(\bR\x05isAlt\"\x9c\x03\n" +
	"\x13CreateFieldsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adefault\x18\x02 \x01(\tR\adefault\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05index\x18\x04 \x01(\tR\x05index\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x127\n" +
	"\n" +
	"attributes\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"is_visible\x18\t \x01(\bR\tisVisible\x12\x16\n" +
	"\x06unique\x18\n" +
	" \x01(\bR\x06unique\x12\x1c\n" +
	"\tautomatic\x18\v \x01(\bR\tautomatic\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x12\x1b\n" +
	"\tcommit_id\x18\r \x01(\tR\bcommitId\x12!\n" +
	"\fminio_folder\x18\x0e \x01(\tR\vminioFolder\"\xc7\x06\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adefault\x18\x02 \x01(\tR\adefault\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05index\x18\x04 \x01(\tR\x05index\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\x19\n" +
	"\btable_id\x18\a \x01(\tR\atableId\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x127\n" +
	"\n" +
	"attributes\x18\t \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"is_visible\x18\n" +
	" \x01(\bR\tisVisible\x12%\n" +
	"\x0eautofill_field\x18\v \x01(\tR\rautofillField\x12%\n" +
	"\x0eautofill_table\x18\f \x01(\tR\rautofillTable\x12\x1f\n" +
	"\vrelation_id\x18\r \x01(\tR\n" +
	"relationId\x12\x16\n" +
	"\x06unique\x18\x0e \x01(\bR\x06unique\x12\x1c\n" +
	"\tautomatic\x18\x0f \x01(\bR\tautomatic\x12\x1d\n" +
	"\n" +
	"project_id\x18\x10 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tcommit_id\x18\x11 \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x12 \x01(\tR\tversionId\x12\x1b\n" +
	"\tis_system\x18\x13 \x01(\bR\bisSystem\x12%\n" +
	"\x0erelation_field\x18\x14 \x01(\tR\rrelationField\x12\x1d\n" +
	"\n" +
	"show_label\x18\x15 \x01(\bR\tshowLabel\x121\n" +
	"\x14enable_multilanguage\x18\x16 \x01(\bR\x13enableMultilanguage\x12-\n" +
	"\x12hide_multilanguage\x18\x17 \x01(\bR\x11hideMultilanguage\x12!\n" +
	"\fminio_folder\x18\x18 \x01(\tR\vminioFolder\x12\x15\n" +
	"\x06env_id\x18\x19 \x01(\tR\x05envId\x12\x1b\n" +
	"\tis_search\x18\x1a \x01(\bR\bisSearch\x12\x15\n" +
	"\x06is_alt\x18\x1b \x01(\bR\x05isAlt\";\n" +
	"\fSearchUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tis_search\x18\x02 \x01(\bR\bisSearch\"\x91\x01\n" +
	"\x13SearchUpdateRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x02 \x01(\tR\ttableSlug\x12<\n" +
	"\x06fields\x18\x03 \x03(\v2$.object_builder_service.SearchUpdateR\x06fields\"\x90\x01\n" +
	"\x14GetAllFieldsResponse\x125\n" +
	"\x06fields\x18\x01 \x03(\v2\x1d.object_builder_service.FieldR\x06fields\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xc6\x02\n" +
	"\x13GetAllFieldsRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x05 \x01(\tR\ttableSlug\x12,\n" +
	"\x12with_many_relation\x18\x06 \x01(\bR\x10withManyRelation\x12*\n" +
	"\x11with_one_relation\x18\a \x01(\bR\x0fwithOneRelation\x12\x17\n" +
	"\arole_id\x18\b \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"version_id\x18\n" +
	" \x01(\tR\tversionId\"W\n" +
	"\x0fFieldPrimaryKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x15\n" +
	"\x06env_id\x18\x03 \x01(\tR\x05envId\"\xe8\x01\n" +
	"\x1bGetAllFieldsForItemsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12+\n" +
	"\x11language_settings\x18\x05 \x01(\tR\x10languageSettings\x12%\n" +
	"\x0ewith_relations\x18\x06 \x01(\bR\rwithRelations\"X\n" +
	"\tAllFields\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"m\n" +
	"\x10GetAllByLabelReq\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vfield_label\x18\x02 \x01(\tR\n" +
	"fieldLabel\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\")\n" +
	"\x15GetIdsByLabelResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"m\n" +
	"\x10GetIdsByLabelReq\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vfield_label\x18\x02 \x03(\tR\n" +
	"fieldLabel\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId2\xd2\x06\n" +
	"\fFieldService\x12U\n" +
	"\x06Create\x12*.object_builder_service.CreateFieldRequest\x1a\x1d.object_builder_service.Field\"\x00\x12S\n" +
	"\aGetByID\x12'.object_builder_service.FieldPrimaryKey\x1a\x1d.object_builder_service.Field\"\x00\x12e\n" +
	"\x06GetAll\x12+.object_builder_service.GetAllFieldsRequest\x1a,.object_builder_service.GetAllFieldsResponse\"\x00\x12j\n" +
	"\x0eGetAllForItems\x123.object_builder_service.GetAllFieldsForItemsRequest\x1a!.object_builder_service.AllFields\"\x00\x12H\n" +
	"\x06Update\x12\x1d.object_builder_service.Field\x1a\x1d.object_builder_service.Field\"\x00\x12U\n" +
	"\fUpdateSearch\x12+.object_builder_service.SearchUpdateRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x06Delete\x12'.object_builder_service.FieldPrimaryKey\x1a\x16.google.protobuf.Empty\"\x00\x12i\n" +
	"\rGetAllByLabel\x12(.object_builder_service.GetAllByLabelReq\x1a,.object_builder_service.GetAllFieldsResponse\"\x00\x12j\n" +
	"\rGetIdsByLabel\x12(.object_builder_service.GetIdsByLabelReq\x1a-.object_builder_service.GetIdsByLabelResponse\"\x00B!Z\x1fgenproto/object_builder_serviceb\x06proto3"

var (
	file_field_proto_rawDescOnce sync.Once
	file_field_proto_rawDescData []byte
)

func file_field_proto_rawDescGZIP() []byte {
	file_field_proto_rawDescOnce.Do(func() {
		file_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_field_proto_rawDesc), len(file_field_proto_rawDesc)))
	})
	return file_field_proto_rawDescData
}

var file_field_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_field_proto_goTypes = []any{
	(*CreateFieldRequest)(nil),          // 0: object_builder_service.CreateFieldRequest
	(*CreateFieldsRequest)(nil),         // 1: object_builder_service.CreateFieldsRequest
	(*Field)(nil),                       // 2: object_builder_service.Field
	(*SearchUpdate)(nil),                // 3: object_builder_service.SearchUpdate
	(*SearchUpdateRequest)(nil),         // 4: object_builder_service.SearchUpdateRequest
	(*GetAllFieldsResponse)(nil),        // 5: object_builder_service.GetAllFieldsResponse
	(*GetAllFieldsRequest)(nil),         // 6: object_builder_service.GetAllFieldsRequest
	(*FieldPrimaryKey)(nil),             // 7: object_builder_service.FieldPrimaryKey
	(*GetAllFieldsForItemsRequest)(nil), // 8: object_builder_service.GetAllFieldsForItemsRequest
	(*AllFields)(nil),                   // 9: object_builder_service.AllFields
	(*GetAllByLabelReq)(nil),            // 10: object_builder_service.GetAllByLabelReq
	(*GetIdsByLabelResponse)(nil),       // 11: object_builder_service.GetIdsByLabelResponse
	(*GetIdsByLabelReq)(nil),            // 12: object_builder_service.GetIdsByLabelReq
	(*_struct.Struct)(nil),              // 13: google.protobuf.Struct
	(*empty.Empty)(nil),                 // 14: google.protobuf.Empty
}
var file_field_proto_depIdxs = []int32{
	13, // 0: object_builder_service.CreateFieldRequest.attributes:type_name -> google.protobuf.Struct
	13, // 1: object_builder_service.CreateFieldsRequest.attributes:type_name -> google.protobuf.Struct
	13, // 2: object_builder_service.Field.attributes:type_name -> google.protobuf.Struct
	3,  // 3: object_builder_service.SearchUpdateRequest.fields:type_name -> object_builder_service.SearchUpdate
	2,  // 4: object_builder_service.GetAllFieldsResponse.fields:type_name -> object_builder_service.Field
	13, // 5: object_builder_service.GetAllFieldsResponse.data:type_name -> google.protobuf.Struct
	13, // 6: object_builder_service.AllFields.data:type_name -> google.protobuf.Struct
	0,  // 7: object_builder_service.FieldService.Create:input_type -> object_builder_service.CreateFieldRequest
	7,  // 8: object_builder_service.FieldService.GetByID:input_type -> object_builder_service.FieldPrimaryKey
	6,  // 9: object_builder_service.FieldService.GetAll:input_type -> object_builder_service.GetAllFieldsRequest
	8,  // 10: object_builder_service.FieldService.GetAllForItems:input_type -> object_builder_service.GetAllFieldsForItemsRequest
	2,  // 11: object_builder_service.FieldService.Update:input_type -> object_builder_service.Field
	4,  // 12: object_builder_service.FieldService.UpdateSearch:input_type -> object_builder_service.SearchUpdateRequest
	7,  // 13: object_builder_service.FieldService.Delete:input_type -> object_builder_service.FieldPrimaryKey
	10, // 14: object_builder_service.FieldService.GetAllByLabel:input_type -> object_builder_service.GetAllByLabelReq
	12, // 15: object_builder_service.FieldService.GetIdsByLabel:input_type -> object_builder_service.GetIdsByLabelReq
	2,  // 16: object_builder_service.FieldService.Create:output_type -> object_builder_service.Field
	2,  // 17: object_builder_service.FieldService.GetByID:output_type -> object_builder_service.Field
	5,  // 18: object_builder_service.FieldService.GetAll:output_type -> object_builder_service.GetAllFieldsResponse
	9,  // 19: object_builder_service.FieldService.GetAllForItems:output_type -> object_builder_service.AllFields
	2,  // 20: object_builder_service.FieldService.Update:output_type -> object_builder_service.Field
	14, // 21: object_builder_service.FieldService.UpdateSearch:output_type -> google.protobuf.Empty
	14, // 22: object_builder_service.FieldService.Delete:output_type -> google.protobuf.Empty
	5,  // 23: object_builder_service.FieldService.GetAllByLabel:output_type -> object_builder_service.GetAllFieldsResponse
	11, // 24: object_builder_service.FieldService.GetIdsByLabel:output_type -> object_builder_service.GetIdsByLabelResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_field_proto_init() }
func file_field_proto_init() {
	if File_field_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_field_proto_rawDesc), len(file_field_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_field_proto_goTypes,
		DependencyIndexes: file_field_proto_depIdxs,
		MessageInfos:      file_field_proto_msgTypes,
	}.Build()
	File_field_proto = out.File
	file_field_proto_goTypes = nil
	file_field_proto_depIdxs = nil
}
