// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: object_builder_service.proto

package object_builder_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_object_builder_service_proto protoreflect.FileDescriptor

const file_object_builder_service_proto_rawDesc = "" +
	"\n" +
	"\x1cobject_builder_service.proto\x12\x16object_builder_service\x1a\vtable.proto\x1a\x14object_builder.proto\x1a\rsection.proto\x1a\x0erelation.proto\x1a\n" +
	"view.proto\x1a\tapp.proto\x1a\x0fdashboard.proto\x1a\x0evariable.proto\x1a\vpanel.proto\x1a\x13html_template.proto\x1a\vlogin.proto\x1a\x0edocument.proto\x1a\vevent.proto\x1a\x10event_logs.proto\x1a\vexcel.proto\x1a\x10permission.proto\x1a\x12custom_event.proto\x1a\rbarcode.proto\x1a\x0efunction.proto\x1a\x12query_folder.proto\x1a\x0equeryies.proto\x1a\x0fweb_pages.proto\x1a\x0fcascading.proto\x1a\x15builder_project.proto\x1a!object_builder_ping_service.proto\x1a\x13table_helpers.proto\x1a\x1afields_and_relations.proto\x1a\rsetting.proto\x1a\x12table_folder.proto\x1a\flayout.proto\x1a\n" +
	"menu.proto\x1a\x1acustom_error_message.proto\x1a\x1creport_setting_service.proto\x1a\vitems.proto\x1a\n" +
	"file.proto\x1a\x16request_analytic.proto\x1a\x15version_history.proto\x1a\rversion.proto\x1a\x0elanguage.protoB!Z\x1fgenproto/object_builder_serviceb\x06proto3"

var file_object_builder_service_proto_goTypes = []any{}
var file_object_builder_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_object_builder_service_proto_init() }
func file_object_builder_service_proto_init() {
	if File_object_builder_service_proto != nil {
		return
	}
	file_table_proto_init()
	file_object_builder_proto_init()
	file_section_proto_init()
	file_relation_proto_init()
	file_view_proto_init()
	file_app_proto_init()
	file_dashboard_proto_init()
	file_variable_proto_init()
	file_panel_proto_init()
	file_html_template_proto_init()
	file_login_proto_init()
	file_document_proto_init()
	file_event_proto_init()
	file_event_logs_proto_init()
	file_excel_proto_init()
	file_permission_proto_init()
	file_custom_event_proto_init()
	file_barcode_proto_init()
	file_function_proto_init()
	file_query_folder_proto_init()
	file_queryies_proto_init()
	file_web_pages_proto_init()
	file_cascading_proto_init()
	file_builder_project_proto_init()
	file_object_builder_ping_service_proto_init()
	file_table_helpers_proto_init()
	file_fields_and_relations_proto_init()
	file_setting_proto_init()
	file_table_folder_proto_init()
	file_layout_proto_init()
	file_menu_proto_init()
	file_custom_error_message_proto_init()
	file_report_setting_service_proto_init()
	file_items_proto_init()
	file_file_proto_init()
	file_request_analytic_proto_init()
	file_version_history_proto_init()
	file_version_proto_init()
	file_language_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_object_builder_service_proto_rawDesc), len(file_object_builder_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_object_builder_service_proto_goTypes,
		DependencyIndexes: file_object_builder_service_proto_depIdxs,
	}.Build()
	File_object_builder_service_proto = out.File
	file_object_builder_service_proto_goTypes = nil
	file_object_builder_service_proto_depIdxs = nil
}
