// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: panel.proto

package object_builder_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePanelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Coordinates   []int32                `protobuf:"varint,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Attributes    *_struct.Struct        `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	DashboardId   string                 `protobuf:"bytes,5,opt,name=dashboard_id,json=dashboardId,proto3" json:"dashboard_id,omitempty"`
	HasPagination bool                   `protobuf:"varint,6,opt,name=has_pagination,json=hasPagination,proto3" json:"has_pagination,omitempty"`
	ProjectId     string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitId      int64                  `protobuf:"varint,8,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CommitGuid    string                 `protobuf:"bytes,9,opt,name=commit_guid,json=commitGuid,proto3" json:"commit_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePanelRequest) Reset() {
	*x = CreatePanelRequest{}
	mi := &file_panel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePanelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePanelRequest) ProtoMessage() {}

func (x *CreatePanelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePanelRequest.ProtoReflect.Descriptor instead.
func (*CreatePanelRequest) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePanelRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CreatePanelRequest) GetCoordinates() []int32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *CreatePanelRequest) GetAttributes() *_struct.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreatePanelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePanelRequest) GetDashboardId() string {
	if x != nil {
		return x.DashboardId
	}
	return ""
}

func (x *CreatePanelRequest) GetHasPagination() bool {
	if x != nil {
		return x.HasPagination
	}
	return false
}

func (x *CreatePanelRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreatePanelRequest) GetCommitId() int64 {
	if x != nil {
		return x.CommitId
	}
	return 0
}

func (x *CreatePanelRequest) GetCommitGuid() string {
	if x != nil {
		return x.CommitGuid
	}
	return ""
}

type Panel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Coordinates   []int32                `protobuf:"varint,3,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Attributes    *_struct.Struct        `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	DashboardId   string                 `protobuf:"bytes,6,opt,name=dashboard_id,json=dashboardId,proto3" json:"dashboard_id,omitempty"`
	HasPagination bool                   `protobuf:"varint,7,opt,name=has_pagination,json=hasPagination,proto3" json:"has_pagination,omitempty"`
	ProjectId     string                 `protobuf:"bytes,8,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Panel) Reset() {
	*x = Panel{}
	mi := &file_panel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Panel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panel) ProtoMessage() {}

func (x *Panel) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panel.ProtoReflect.Descriptor instead.
func (*Panel) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{1}
}

func (x *Panel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Panel) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Panel) GetCoordinates() []int32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Panel) GetAttributes() *_struct.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Panel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Panel) GetDashboardId() string {
	if x != nil {
		return x.DashboardId
	}
	return ""
}

func (x *Panel) GetHasPagination() bool {
	if x != nil {
		return x.HasPagination
	}
	return false
}

func (x *Panel) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetAllPanelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Panels        []*Panel               `protobuf:"bytes,1,rep,name=panels,proto3" json:"panels,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPanelsResponse) Reset() {
	*x = GetAllPanelsResponse{}
	mi := &file_panel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPanelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPanelsResponse) ProtoMessage() {}

func (x *GetAllPanelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPanelsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPanelsResponse) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllPanelsResponse) GetPanels() []*Panel {
	if x != nil {
		return x.Panels
	}
	return nil
}

func (x *GetAllPanelsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetAllPanelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPanelsRequest) Reset() {
	*x = GetAllPanelsRequest{}
	mi := &file_panel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPanelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPanelsRequest) ProtoMessage() {}

func (x *GetAllPanelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPanelsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPanelsRequest) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPanelsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAllPanelsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type PanelPrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelPrimaryKey) Reset() {
	*x = PanelPrimaryKey{}
	mi := &file_panel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelPrimaryKey) ProtoMessage() {}

func (x *PanelPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelPrimaryKey.ProtoReflect.Descriptor instead.
func (*PanelPrimaryKey) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{4}
}

func (x *PanelPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PanelPrimaryKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type PanelCoordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coordinates   []int32                `protobuf:"varint,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelCoordinates) Reset() {
	*x = PanelCoordinates{}
	mi := &file_panel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelCoordinates) ProtoMessage() {}

func (x *PanelCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelCoordinates.ProtoReflect.Descriptor instead.
func (*PanelCoordinates) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{5}
}

func (x *PanelCoordinates) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PanelCoordinates) GetCoordinates() []int32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type UpdatePanelCoordinatesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PanelCoordinates []*PanelCoordinates    `protobuf:"bytes,1,rep,name=panel_coordinates,json=panelCoordinates,proto3" json:"panel_coordinates,omitempty"`
	ProjectId        string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatePanelCoordinatesRequest) Reset() {
	*x = UpdatePanelCoordinatesRequest{}
	mi := &file_panel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePanelCoordinatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePanelCoordinatesRequest) ProtoMessage() {}

func (x *UpdatePanelCoordinatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePanelCoordinatesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePanelCoordinatesRequest) Descriptor() ([]byte, []int) {
	return file_panel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePanelCoordinatesRequest) GetPanelCoordinates() []*PanelCoordinates {
	if x != nil {
		return x.PanelCoordinates
	}
	return nil
}

func (x *UpdatePanelCoordinatesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_panel_proto protoreflect.FileDescriptor

const file_panel_proto_rawDesc = "" +
	"\n" +
	"\vpanel.proto\x12\x16object_builder_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc2\x02\n" +
	"\x12CreatePanelRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12 \n" +
	"\vcoordinates\x18\x02 \x03(\x05R\vcoordinates\x127\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12!\n" +
	"\fdashboard_id\x18\x05 \x01(\tR\vdashboardId\x12%\n" +
	"\x0ehas_pagination\x18\x06 \x01(\bR\rhasPagination\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x1b\n" +
	"\tcommit_id\x18\b \x01(\x03R\bcommitId\x12\x1f\n" +
	"\vcommit_guid\x18\t \x01(\tR\n" +
	"commitGuid\"\x87\x02\n" +
	"\x05Panel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12 \n" +
	"\vcoordinates\x18\x03 \x03(\x05R\vcoordinates\x127\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12!\n" +
	"\fdashboard_id\x18\x06 \x01(\tR\vdashboardId\x12%\n" +
	"\x0ehas_pagination\x18\a \x01(\bR\rhasPagination\x12\x1d\n" +
	"\n" +
	"project_id\x18\b \x01(\tR\tprojectId\"c\n" +
	"\x14GetAllPanelsResponse\x125\n" +
	"\x06panels\x18\x01 \x03(\v2\x1d.object_builder_service.PanelR\x06panels\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"J\n" +
	"\x13GetAllPanelsRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"@\n" +
	"\x0fPanelPrimaryKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"D\n" +
	"\x10PanelCoordinates\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vcoordinates\x18\x02 \x03(\x05R\vcoordinates\"\x95\x01\n" +
	"\x1dUpdatePanelCoordinatesRequest\x12U\n" +
	"\x11panel_coordinates\x18\x01 \x03(\v2(.object_builder_service.PanelCoordinatesR\x10panelCoordinates\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId2\x9a\x04\n" +
	"\fPanelService\x12U\n" +
	"\x06Create\x12*.object_builder_service.CreatePanelRequest\x1a\x1d.object_builder_service.Panel\"\x00\x12f\n" +
	"\aGetList\x12+.object_builder_service.GetAllPanelsRequest\x1a,.object_builder_service.GetAllPanelsResponse\"\x00\x12U\n" +
	"\tGetSingle\x12'.object_builder_service.PanelPrimaryKey\x1a\x1d.object_builder_service.Panel\"\x00\x12A\n" +
	"\x06Update\x12\x1d.object_builder_service.Panel\x1a\x16.google.protobuf.Empty\"\x00\x12d\n" +
	"\x11UpdateCoordinates\x125.object_builder_service.UpdatePanelCoordinatesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x06Delete\x12'.object_builder_service.PanelPrimaryKey\x1a\x16.google.protobuf.Empty\"\x00B!Z\x1fgenproto/object_builder_serviceb\x06proto3"

var (
	file_panel_proto_rawDescOnce sync.Once
	file_panel_proto_rawDescData []byte
)

func file_panel_proto_rawDescGZIP() []byte {
	file_panel_proto_rawDescOnce.Do(func() {
		file_panel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panel_proto_rawDesc), len(file_panel_proto_rawDesc)))
	})
	return file_panel_proto_rawDescData
}

var file_panel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_panel_proto_goTypes = []any{
	(*CreatePanelRequest)(nil),            // 0: object_builder_service.CreatePanelRequest
	(*Panel)(nil),                         // 1: object_builder_service.Panel
	(*GetAllPanelsResponse)(nil),          // 2: object_builder_service.GetAllPanelsResponse
	(*GetAllPanelsRequest)(nil),           // 3: object_builder_service.GetAllPanelsRequest
	(*PanelPrimaryKey)(nil),               // 4: object_builder_service.PanelPrimaryKey
	(*PanelCoordinates)(nil),              // 5: object_builder_service.PanelCoordinates
	(*UpdatePanelCoordinatesRequest)(nil), // 6: object_builder_service.UpdatePanelCoordinatesRequest
	(*_struct.Struct)(nil),                // 7: google.protobuf.Struct
	(*empty.Empty)(nil),                   // 8: google.protobuf.Empty
}
var file_panel_proto_depIdxs = []int32{
	7,  // 0: object_builder_service.CreatePanelRequest.attributes:type_name -> google.protobuf.Struct
	7,  // 1: object_builder_service.Panel.attributes:type_name -> google.protobuf.Struct
	1,  // 2: object_builder_service.GetAllPanelsResponse.panels:type_name -> object_builder_service.Panel
	5,  // 3: object_builder_service.UpdatePanelCoordinatesRequest.panel_coordinates:type_name -> object_builder_service.PanelCoordinates
	0,  // 4: object_builder_service.PanelService.Create:input_type -> object_builder_service.CreatePanelRequest
	3,  // 5: object_builder_service.PanelService.GetList:input_type -> object_builder_service.GetAllPanelsRequest
	4,  // 6: object_builder_service.PanelService.GetSingle:input_type -> object_builder_service.PanelPrimaryKey
	1,  // 7: object_builder_service.PanelService.Update:input_type -> object_builder_service.Panel
	6,  // 8: object_builder_service.PanelService.UpdateCoordinates:input_type -> object_builder_service.UpdatePanelCoordinatesRequest
	4,  // 9: object_builder_service.PanelService.Delete:input_type -> object_builder_service.PanelPrimaryKey
	1,  // 10: object_builder_service.PanelService.Create:output_type -> object_builder_service.Panel
	2,  // 11: object_builder_service.PanelService.GetList:output_type -> object_builder_service.GetAllPanelsResponse
	1,  // 12: object_builder_service.PanelService.GetSingle:output_type -> object_builder_service.Panel
	8,  // 13: object_builder_service.PanelService.Update:output_type -> google.protobuf.Empty
	8,  // 14: object_builder_service.PanelService.UpdateCoordinates:output_type -> google.protobuf.Empty
	8,  // 15: object_builder_service.PanelService.Delete:output_type -> google.protobuf.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_panel_proto_init() }
func file_panel_proto_init() {
	if File_panel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panel_proto_rawDesc), len(file_panel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panel_proto_goTypes,
		DependencyIndexes: file_panel_proto_depIdxs,
		MessageInfos:      file_panel_proto_msgTypes,
	}.Build()
	File_panel_proto = out.File
	file_panel_proto_goTypes = nil
	file_panel_proto_depIdxs = nil
}
