// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: service_resource.proto

package company_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceResourceModel struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceType           ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=company_service.ServiceType" json:"service_type,omitempty"`
	ProjectId             string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,6,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	ResourceId            string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	EnvironmentId         string                 `protobuf:"bytes,8,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ResourceType          ResourceType           `protobuf:"varint,9,opt,name=resource_type,json=resourceType,proto3,enum=company_service.ResourceType" json:"resource_type,omitempty"`
	NodeType              string                 `protobuf:"bytes,10,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	ProjectStatus         string                 `protobuf:"bytes,11,opt,name=project_status,json=projectStatus,proto3" json:"project_status,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServiceResourceModel) Reset() {
	*x = ServiceResourceModel{}
	mi := &file_service_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResourceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResourceModel) ProtoMessage() {}

func (x *ServiceResourceModel) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResourceModel.ProtoReflect.Descriptor instead.
func (*ServiceResourceModel) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceResourceModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceResourceModel) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_NOT_SPECIFIED
}

func (x *ServiceResourceModel) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ServiceResourceModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ServiceResourceModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceResourceModel) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *ServiceResourceModel) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ServiceResourceModel) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ServiceResourceModel) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_NOT_DECIDED
}

func (x *ServiceResourceModel) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ServiceResourceModel) GetProjectStatus() string {
	if x != nil {
		return x.ProjectStatus
	}
	return ""
}

type GetListServiceResourceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListServiceResourceReq) Reset() {
	*x = GetListServiceResourceReq{}
	mi := &file_service_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListServiceResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListServiceResourceReq) ProtoMessage() {}

func (x *GetListServiceResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListServiceResourceReq.ProtoReflect.Descriptor instead.
func (*GetListServiceResourceReq) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{1}
}

func (x *GetListServiceResourceReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetListServiceResourceReq) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *GetListServiceResourceReq) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetListServiceResourceRes struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	ServiceResources map[string]*ServiceResourceModel `protobuf:"bytes,1,rep,name=service_resources,json=serviceResources,proto3" json:"service_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources        []*Resource                      `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	ResourceTypes    map[int32]string                 `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetListServiceResourceRes) Reset() {
	*x = GetListServiceResourceRes{}
	mi := &file_service_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListServiceResourceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListServiceResourceRes) ProtoMessage() {}

func (x *GetListServiceResourceRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListServiceResourceRes.ProtoReflect.Descriptor instead.
func (*GetListServiceResourceRes) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{2}
}

func (x *GetListServiceResourceRes) GetServiceResources() map[string]*ServiceResourceModel {
	if x != nil {
		return x.ServiceResources
	}
	return nil
}

func (x *GetListServiceResourceRes) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GetListServiceResourceRes) GetResourceTypes() map[int32]string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

type GetSingleServiceResourceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,4,opt,name=service_type,json=serviceType,proto3,enum=company_service.ServiceType" json:"service_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSingleServiceResourceReq) Reset() {
	*x = GetSingleServiceResourceReq{}
	mi := &file_service_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleServiceResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleServiceResourceReq) ProtoMessage() {}

func (x *GetSingleServiceResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleServiceResourceReq.ProtoReflect.Descriptor instead.
func (*GetSingleServiceResourceReq) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{3}
}

func (x *GetSingleServiceResourceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSingleServiceResourceReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetSingleServiceResourceReq) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *GetSingleServiceResourceReq) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_NOT_SPECIFIED
}

type UpdateServiceResourceReq struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	ServiceResources []*ServiceResourceModel `protobuf:"bytes,1,rep,name=service_resources,json=serviceResources,proto3" json:"service_resources,omitempty"`
	ProjectId        string                  `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId    string                  `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServiceResourceReq) Reset() {
	*x = UpdateServiceResourceReq{}
	mi := &file_service_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResourceReq) ProtoMessage() {}

func (x *UpdateServiceResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResourceReq.ProtoReflect.Descriptor instead.
func (*UpdateServiceResourceReq) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateServiceResourceReq) GetServiceResources() []*ServiceResourceModel {
	if x != nil {
		return x.ServiceResources
	}
	return nil
}

func (x *UpdateServiceResourceReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateServiceResourceReq) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type UpdateServiceResourceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int32                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceResourceRes) Reset() {
	*x = UpdateServiceResourceRes{}
	mi := &file_service_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResourceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResourceRes) ProtoMessage() {}

func (x *UpdateServiceResourceRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResourceRes.ProtoReflect.Descriptor instead.
func (*UpdateServiceResourceRes) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateServiceResourceRes) GetRowsAffected() int32 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

type GetListServiceResourceRes_ResourceTypeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListServiceResourceRes_ResourceTypeList) Reset() {
	*x = GetListServiceResourceRes_ResourceTypeList{}
	mi := &file_service_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListServiceResourceRes_ResourceTypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListServiceResourceRes_ResourceTypeList) ProtoMessage() {}

func (x *GetListServiceResourceRes_ResourceTypeList) ProtoReflect() protoreflect.Message {
	mi := &file_service_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListServiceResourceRes_ResourceTypeList.ProtoReflect.Descriptor instead.
func (*GetListServiceResourceRes_ResourceTypeList) Descriptor() ([]byte, []int) {
	return file_service_resource_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetListServiceResourceRes_ResourceTypeList) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetListServiceResourceRes_ResourceTypeList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_service_resource_proto protoreflect.FileDescriptor

const file_service_resource_proto_rawDesc = "" +
	"\n" +
	"\x16service_resource.proto\x12\x0fcompany_service\x1a\x16projects_service.proto\x1a\rcompany.proto\"\xc6\x03\n" +
	"\x14ServiceResourceModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x1c.company_service.ServiceTypeR\vserviceType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x126\n" +
	"\x17resource_environment_id\x18\x06 \x01(\tR\x15resourceEnvironmentId\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12%\n" +
	"\x0eenvironment_id\x18\b \x01(\tR\renvironmentId\x12B\n" +
	"\rresource_type\x18\t \x01(\x0e2\x1d.company_service.ResourceTypeR\fresourceType\x12\x1b\n" +
	"\tnode_type\x18\n" +
	" \x01(\tR\bnodeType\x12%\n" +
	"\x0eproject_status\x18\v \x01(\tR\rprojectStatus\"\x82\x01\n" +
	"\x19GetListServiceResourceReq\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"\x8f\x04\n" +
	"\x19GetListServiceResourceRes\x12m\n" +
	"\x11service_resources\x18\x01 \x03(\v2@.company_service.GetListServiceResourceRes.ServiceResourcesEntryR\x10serviceResources\x127\n" +
	"\tresources\x18\x02 \x03(\v2\x19.company_service.ResourceR\tresources\x12d\n" +
	"\x0eresource_types\x18\x03 \x03(\v2=.company_service.GetListServiceResourceRes.ResourceTypesEntryR\rresourceTypes\x1a6\n" +
	"\x10ResourceTypeList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1aj\n" +
	"\x15ServiceResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.company_service.ServiceResourceModelR\x05value:\x028\x01\x1a@\n" +
	"\x12ResourceTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x1bGetSingleServiceResourceReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12%\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tR\renvironmentId\x12?\n" +
	"\fservice_type\x18\x04 \x01(\x0e2\x1c.company_service.ServiceTypeR\vserviceType\"\xb4\x01\n" +
	"\x18UpdateServiceResourceReq\x12R\n" +
	"\x11service_resources\x18\x01 \x03(\v2%.company_service.ServiceResourceModelR\x10serviceResources\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12%\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tR\renvironmentId\"?\n" +
	"\x18UpdateServiceResourceRes\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x05R\frowsAffected2\xc1\x02\n" +
	"\x14MicroserviceResource\x12c\n" +
	"\aGetList\x12*.company_service.GetListServiceResourceReq\x1a*.company_service.GetListServiceResourceRes\"\x00\x12`\n" +
	"\x06Update\x12).company_service.UpdateServiceResourceReq\x1a).company_service.UpdateServiceResourceRes\"\x00\x12b\n" +
	"\tGetSingle\x12,.company_service.GetSingleServiceResourceReq\x1a%.company_service.ServiceResourceModel\"\x00B\x1aZ\x18genproto/company_serviceb\x06proto3"

var (
	file_service_resource_proto_rawDescOnce sync.Once
	file_service_resource_proto_rawDescData []byte
)

func file_service_resource_proto_rawDescGZIP() []byte {
	file_service_resource_proto_rawDescOnce.Do(func() {
		file_service_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_resource_proto_rawDesc), len(file_service_resource_proto_rawDesc)))
	})
	return file_service_resource_proto_rawDescData
}

var file_service_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_resource_proto_goTypes = []any{
	(*ServiceResourceModel)(nil),                       // 0: company_service.ServiceResourceModel
	(*GetListServiceResourceReq)(nil),                  // 1: company_service.GetListServiceResourceReq
	(*GetListServiceResourceRes)(nil),                  // 2: company_service.GetListServiceResourceRes
	(*GetSingleServiceResourceReq)(nil),                // 3: company_service.GetSingleServiceResourceReq
	(*UpdateServiceResourceReq)(nil),                   // 4: company_service.UpdateServiceResourceReq
	(*UpdateServiceResourceRes)(nil),                   // 5: company_service.UpdateServiceResourceRes
	(*GetListServiceResourceRes_ResourceTypeList)(nil), // 6: company_service.GetListServiceResourceRes.ResourceTypeList
	nil,               // 7: company_service.GetListServiceResourceRes.ServiceResourcesEntry
	nil,               // 8: company_service.GetListServiceResourceRes.ResourceTypesEntry
	(ServiceType)(0),  // 9: company_service.ServiceType
	(ResourceType)(0), // 10: company_service.ResourceType
	(*Resource)(nil),  // 11: company_service.Resource
}
var file_service_resource_proto_depIdxs = []int32{
	9,  // 0: company_service.ServiceResourceModel.service_type:type_name -> company_service.ServiceType
	10, // 1: company_service.ServiceResourceModel.resource_type:type_name -> company_service.ResourceType
	7,  // 2: company_service.GetListServiceResourceRes.service_resources:type_name -> company_service.GetListServiceResourceRes.ServiceResourcesEntry
	11, // 3: company_service.GetListServiceResourceRes.resources:type_name -> company_service.Resource
	8,  // 4: company_service.GetListServiceResourceRes.resource_types:type_name -> company_service.GetListServiceResourceRes.ResourceTypesEntry
	9,  // 5: company_service.GetSingleServiceResourceReq.service_type:type_name -> company_service.ServiceType
	0,  // 6: company_service.UpdateServiceResourceReq.service_resources:type_name -> company_service.ServiceResourceModel
	0,  // 7: company_service.GetListServiceResourceRes.ServiceResourcesEntry.value:type_name -> company_service.ServiceResourceModel
	1,  // 8: company_service.MicroserviceResource.GetList:input_type -> company_service.GetListServiceResourceReq
	4,  // 9: company_service.MicroserviceResource.Update:input_type -> company_service.UpdateServiceResourceReq
	3,  // 10: company_service.MicroserviceResource.GetSingle:input_type -> company_service.GetSingleServiceResourceReq
	2,  // 11: company_service.MicroserviceResource.GetList:output_type -> company_service.GetListServiceResourceRes
	5,  // 12: company_service.MicroserviceResource.Update:output_type -> company_service.UpdateServiceResourceRes
	0,  // 13: company_service.MicroserviceResource.GetSingle:output_type -> company_service.ServiceResourceModel
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_resource_proto_init() }
func file_service_resource_proto_init() {
	if File_service_resource_proto != nil {
		return
	}
	file_projects_service_proto_init()
	file_company_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_resource_proto_rawDesc), len(file_service_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_resource_proto_goTypes,
		DependencyIndexes: file_service_resource_proto_depIdxs,
		MessageInfos:      file_service_resource_proto_msgTypes,
	}.Build()
	File_service_resource_proto = out.File
	file_service_resource_proto_goTypes = nil
	file_service_resource_proto_depIdxs = nil
}
