package v1

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"time"

	"ucode/ucode_go_api_gateway/api/models"
)

type SSEEventType = string

const (
	EvProgress   SSEEventType = "progress"
	EvProvider   SSEEventType = "provider"
	EvPlan       SSEEventType = "plan"
	EvTableStart SSEEventType = "table_start"
	EvTableDone  SSEEventType = "table_done"
	EvManifest   SSEEventType = "manifest"
	EvChunkStart SSEEventType = "chunk_start"
	EvChunkDone  SSEEventType = "chunk_done"
	EvRepair     SSEEventType = "repair"
	EvPublish    SSEEventType = "publish"
	EvMobileProj SSEEventType = "mobile_project"
	EvDone       SSEEventType = "done"
	EvError      SSEEventType = "error"
	// EvWarning marks a recoverable problem the AI ran into (e.g. a single tool
	// call failed) — generation continues. Distinct from the terminal EvError so
	// the frontend can render it as an inline note instead of a fatal banner.
	EvWarning SSEEventType = "warning"
)

const (
	// Status & feedback
	IconCheckCircle   = "check-circle"   // success, done
	IconAlertCircle   = "alert-circle"   // error
	IconAlertTriangle = "alert-triangle" // warning, partial error
	IconBan           = "ban"            // hard stop (e.g. token limit)

	// AI / generation
	IconSparkles = "sparkles" // AI start, initial prompt
	IconBrain    = "brain"    // model thinking / heartbeat
	IconCPU      = "cpu"      // active model / provider
	IconZap      = "zap"      // parallel generation
	IconBot      = "bot"      // agent design

	// Schema building (ucode)
	IconDatabase   = "database"    // table create/done
	IconColumns    = "columns"     // field added
	IconLink       = "link"        // relation created
	IconFolder     = "folder"      // menu folder
	IconFolderOpen = "folder-open" // folder open / browse
	IconFolderPlus = "folder-plus" // new folder created
	IconPlusCircle = "plus-circle" // insert rows / add item

	// Code / files
	IconCode      = "code-2"    // code generation / editing
	IconFileText  = "file-text" // document / page / file
	IconFileDiff  = "file-diff" // diff / planner output
	IconFileEdit  = "file-edit" // editing existing file
	IconFilePlus  = "file-plus" // creating new file
	IconFileCode  = "file-code" // source code file
	IconListTree  = "list-tree" // file/page structure
	IconGitBranch = "git-branch"

	// Project / publish
	IconUploadCloud  = "upload-cloud"        // deploy / publish
	IconScanSearch   = "scan-search"         // analyse / inspect
	IconPackage      = "package"             // feature chunk
	IconLayers       = "layers"              // UI kit / foundation
	IconLayout       = "layout"              // page layout
	IconPlug         = "plug"                // agent / integration
	IconMousePointer = "mouse-pointer-click" // interactive / visual edit
	IconSmartphone   = "smartphone"          // mobile project
	IconImage        = "image"               // image / photo
	IconGlobe        = "globe"               // public / web
	IconSettings     = "settings"            // config files

	// Auth / roles
	IconShield      = "shield"       // role creation
	IconShieldCheck = "shield-check" // role ready
	IconUsers       = "users"        // client types

	// Agent / tool
	IconWrench = "wrench" // repair / fix
)

// SSEEvent is a single server-sent event in the generation progress stream.
// Icon: Lucide icon name for the frontend to render (e.g. "database", "code-2", "wrench").
// Value: the prominent highlighted value shown larger than Message (e.g. table name, file path).
type SSEEvent struct {
	Type    SSEEventType `json:"type"`
	Message string       `json:"message,omitempty"`
	Value   string       `json:"value,omitempty"`
	Icon    string       `json:"icon,omitempty"`
	Percent int          `json:"percent,omitempty"`
	Data    any          `json:"data,omitempty"`
}

// ProviderEventData identifies the active AI provider and models so the frontend
// can display a "Generated by Gemini 2.5 Pro" badge before generation starts.
type ProviderEventData struct {
	Provider    string `json:"provider"`     // "gemini" | "claude"
	RouterModel string `json:"router_model"` // fast classifier model
	CoderModel  string `json:"coder_model"`  // main code-generation model
}

// PlanEventData carries architect results so the frontend can show planned pages/tables.
type PlanEventData struct {
	ProjectName string   `json:"project_name"`
	ProjectType string   `json:"project_type"`
	Tables      []string `json:"tables"`
	TableCount  int      `json:"table_count"`
}

// ManifestEventData carries manifest results: total files and feature group names.
type ManifestEventData struct {
	TotalFiles   int      `json:"total_files"`
	GroupCount   int      `json:"group_count"`
	FeatureNames []string `json:"feature_names"`
}

// ChunkDoneData carries one completed feature chunk with all its files so the
// frontend can display a live code preview as each feature is generated.
type ChunkDoneData struct {
	Feature string               `json:"feature"`
	Index   int                  `json:"index"`
	Total   int                  `json:"total"`
	Files   []models.ProjectFile `json:"files"`
}

// DoneEventData is the terminal event payload.
type DoneEventData struct {
	Description     string `json:"description"`
	MicrofrontendID string `json:"microfrontend_id,omitempty"`
	McpProjectID    string `json:"mcp_project_id,omitempty"`
	FileCount       int    `json:"file_count,omitempty"`
	DurationSec     int    `json:"duration_sec"`
}

// ProgressEmitter receives generation progress events.
// All Emit calls must be safe from multiple goroutines concurrently.
type ProgressEmitter interface {
	Emit(SSEEvent)
}

// channelEmitter writes progress events without blocking. Terminal and mobile
// delivery events wait for the consumer because losing them breaks the response contract.
type channelEmitter struct {
	ch chan<- SSEEvent
}

func (e *channelEmitter) Emit(ev SSEEvent) {
	// Protect against writes to closed channel if background tasks (e.g. async table creation)
	// outlive the main pipeline and try to emit after eventCh is closed.
	defer func() {
		if r := recover(); r != nil {
			// channel is closed, safely ignore the event
		}
	}()
	if isCriticalSSEEvent(ev.Type) {
		e.ch <- ev
		return
	}
	select {
	case e.ch <- ev:
	default:
	}
}

func isCriticalSSEEvent(eventType SSEEventType) bool {
	return eventType == EvMobileProj || eventType == EvDone || eventType == EvError
}

// noopEmitter discards all events.
// Used when SSE is not requested (backwards-compat with the existing JSON endpoint).
type noopEmitter struct{}

func (noopEmitter) Emit(SSEEvent) {}

func writeSSEEvent(w io.Writer, ev SSEEvent) {
	data, _ := json.Marshal(ev)
	fmt.Fprintf(w, "data: %s\n\n", data)
}

func withHeartbeat(ctx context.Context, emit ProgressEmitter, model string, messages []string, fn func() error) error {
	done := make(chan error, 1)
	go func() { done <- fn() }()

	ticker := time.NewTicker(8 * time.Second)
	defer ticker.Stop()

	msgIdx := 0

	for {
		select {
		case err := <-done:
			return err
		case <-ticker.C:
			emit.Emit(SSEEvent{Type: EvProgress, Icon: "brain", Message: messages[msgIdx%len(messages)], Value: model, Percent: 10})
			msgIdx++
		case <-ctx.Done():
			return ctx.Err()
		}
	}
}

// emitPublishFiles emits per-file publish progress events so the frontend shows
// which files are being deployed. Files are grouped by directory and shown
// with a short delay between groups so the user can follow along.
func emitPublishFiles(emit ProgressEmitter, files []models.ProjectFile, pctStart int) {
	if len(files) == 0 {
		return
	}

	// Group files by top-level directory for cleaner UX.
	type dirGroup struct {
		dir   string
		files []string
	}
	groups := make([]dirGroup, 0)
	seen := make(map[string]int) // dir → index in groups

	for _, f := range files {
		dir := "root"
		if idx := strings.Index(f.Path, "/"); idx != -1 {
			dir = f.Path[:idx]
		}
		if i, ok := seen[dir]; ok {
			groups[i].files = append(groups[i].files, f.Path)
		} else {
			seen[dir] = len(groups)
			groups = append(groups, dirGroup{dir: dir, files: []string{f.Path}})
		}
	}

	emit.Emit(SSEEvent{
		Type:    EvPublish,
		Icon:    "upload-cloud",
		Message: "Публикую проект в GitLab",
		Value:   fmt.Sprintf("%d файлов", len(files)),
		Percent: pctStart,
	})

	for i, g := range groups {
		pct := pctStart + (i+1)*6/len(groups) // spread 6% across groups (93→99)
		if pct > 99 {
			pct = 99
		}

		icon := "file-code"
		switch g.dir {
		case "src":
			icon = "code-2"
		case "public":
			icon = "globe"
		case "root":
			icon = "settings"
		}

		emit.Emit(SSEEvent{
			Type:    EvPublish,
			Icon:    icon,
			Message: fmt.Sprintf("Деплою %s/", g.dir),
			Value:   fmt.Sprintf("%d файлов", len(g.files)),
			Percent: pct,
			Data:    map[string]any{"directory": g.dir, "files": g.files},
		})
	}
}

func newMobileProject(project *models.GeneratedProject, capabilities []models.MobileCapability) *models.MobileProject {
	return &models.MobileProject{
		ProjectName:    project.ProjectName,
		ProjectType:    mobileProjectType,
		Runtime:        mobileRuntime,
		RuntimeVersion: capacitorRuntimeVersion,
		WebDir:         capacitorWebDir,
		Capabilities:   models.CanonicalMobileCapabilities(capabilities),
		Files:          append([]models.ProjectFile(nil), project.Files...),
	}
}

// emitMobileProject sends the installable Capacitor source project to the frontend
// and native build worker. Browser preview remains available through microfrontend publish.
func emitMobileProject(emit ProgressEmitter, project *models.MobileProject) {
	emit.Emit(SSEEvent{
		Type:    EvMobileProj,
		Icon:    "smartphone",
		Message: "Готовлю мобильный проект для Capacitor",
		Value:   fmt.Sprintf("%d файлов", len(project.Files)),
		Percent: 99,
		Data:    project,
	})
}
