// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: user_service.proto

package auth_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingType int32

const (
	SettingType_LANGUAGE SettingType = 0
	// CURRENCY = 1;
	SettingType_TIMEZONE SettingType = 2
)

// Enum value maps for SettingType.
var (
	SettingType_name = map[int32]string{
		0: "LANGUAGE",
		2: "TIMEZONE",
	}
	SettingType_value = map[string]int32{
		"LANGUAGE": 0,
		"TIMEZONE": 2,
	}
)

func (x SettingType) Enum() *SettingType {
	p := new(SettingType)
	*p = x
	return p
}

func (x SettingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_service_proto_enumTypes[0].Descriptor()
}

func (SettingType) Type() protoreflect.EnumType {
	return &file_user_service_proto_enumTypes[0]
}

func (x SettingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingType.Descriptor instead.
func (SettingType) EnumDescriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserByUsernameRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type UserCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectIds    []string               `protobuf:"bytes,2,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCompany) Reset() {
	*x = UserCompany{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCompany) ProtoMessage() {}

func (x *UserCompany) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCompany.ProtoReflect.Descriptor instead.
func (*UserCompany) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserCompany) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserCompany) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

type GetUserProjectsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*UserCompany         `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsRes) Reset() {
	*x = GetUserProjectsRes{}
	mi := &file_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsRes) ProtoMessage() {}

func (x *GetUserProjectsRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsRes.ProtoReflect.Descriptor instead.
func (*GetUserProjectsRes) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProjectsRes) GetCompanies() []*UserCompany {
	if x != nil {
		return x.Companies
	}
	return nil
}

type Setting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *_struct.Struct        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *Setting) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Setting) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetListSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SettingType            `protobuf:"varint,1,opt,name=type,proto3,enum=auth_service.SettingType" json:"type,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	NodeType      string                 `protobuf:"bytes,6,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListSettingReq) Reset() {
	*x = GetListSettingReq{}
	mi := &file_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListSettingReq) ProtoMessage() {}

func (x *GetListSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListSettingReq.ProtoReflect.Descriptor instead.
func (*GetListSettingReq) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetListSettingReq) GetType() SettingType {
	if x != nil {
		return x.Type
	}
	return SettingType_LANGUAGE
}

func (x *GetListSettingReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetListSettingReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetListSettingReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListSettingReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListSettingReq) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type RegisterWithGoogleRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Email                 string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ProjectId             string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CompanyId             string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ClientTypeId          string                 `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,5,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	Name                  string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	ResourceType          int32                  `protobuf:"varint,7,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	NodeType              string                 `protobuf:"bytes,8,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterWithGoogleRequest) Reset() {
	*x = RegisterWithGoogleRequest{}
	mi := &file_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWithGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWithGoogleRequest) ProtoMessage() {}

func (x *RegisterWithGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWithGoogleRequest.ProtoReflect.Descriptor instead.
func (*RegisterWithGoogleRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWithGoogleRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterWithGoogleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RegisterWithGoogleRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *RegisterWithGoogleRequest) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *RegisterWithGoogleRequest) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *RegisterWithGoogleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterWithGoogleRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *RegisterWithGoogleRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type GetUserByLoginTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginTypesResponse) Reset() {
	*x = GetUserByLoginTypesResponse{}
	mi := &file_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginTypesResponse) ProtoMessage() {}

func (x *GetUserByLoginTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginTypesResponse.ProtoReflect.Descriptor instead.
func (*GetUserByLoginTypesResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByLoginTypesResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByLoginTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	ResourceType  int32                  `protobuf:"varint,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	NodeType      string                 `protobuf:"bytes,5,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	ProjectId     string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginTypesRequest) Reset() {
	*x = GetUserByLoginTypesRequest{}
	mi := &file_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginTypesRequest) ProtoMessage() {}

func (x *GetUserByLoginTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginTypesRequest.ProtoReflect.Descriptor instead.
func (*GetUserByLoginTypesRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByLoginTypesRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserByLoginTypesRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserByLoginTypesRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserByLoginTypesRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *GetUserByLoginTypesRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *GetUserByLoginTypesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectsByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsByUserIdReq) Reset() {
	*x = GetProjectsByUserIdReq{}
	mi := &file_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsByUserIdReq) ProtoMessage() {}

func (x *GetProjectsByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetProjectsByUserIdReq) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetProjectsByUserIdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProjectsByUserIdReq) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type UserProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvId         string                 `protobuf:"bytes,2,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProject) Reset() {
	*x = UserProject{}
	mi := &file_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProject) ProtoMessage() {}

func (x *UserProject) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProject.ProtoReflect.Descriptor instead.
func (*UserProject) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *UserProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UserProject) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type GetProjectsByUserIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProjects  []*UserProject         `protobuf:"bytes,1,rep,name=user_projects,json=userProjects,proto3" json:"user_projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsByUserIdRes) Reset() {
	*x = GetProjectsByUserIdRes{}
	mi := &file_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsByUserIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsByUserIdRes) ProtoMessage() {}

func (x *GetProjectsByUserIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsByUserIdRes.ProtoReflect.Descriptor instead.
func (*GetProjectsByUserIdRes) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetProjectsByUserIdRes) GetUserProjects() []*UserProject {
	if x != nil {
		return x.UserProjects
	}
	return nil
}

type AddUserToProjectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Active        int32                  `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	CompanyId     string                 `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ResourceType  int32                  `protobuf:"varint,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ClientTypeId  string                 `protobuf:"bytes,7,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	TableSlug     string                 `protobuf:"bytes,8,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	EnvId         string                 `protobuf:"bytes,9,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,10,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToProjectReq) Reset() {
	*x = AddUserToProjectReq{}
	mi := &file_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToProjectReq) ProtoMessage() {}

func (x *AddUserToProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToProjectReq.ProtoReflect.Descriptor instead.
func (*AddUserToProjectReq) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddUserToProjectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserToProjectReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddUserToProjectReq) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AddUserToProjectReq) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *AddUserToProjectReq) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *AddUserToProjectReq) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *AddUserToProjectReq) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *AddUserToProjectReq) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *AddUserToProjectReq) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *AddUserToProjectReq) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *AddUserToProjectReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddUserToProjectRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TableSlug     string                 `protobuf:"bytes,4,opt,name=table_slug,json=tableSlug,proto3" json:"table_slug,omitempty"`
	ClientTypeId  string                 `protobuf:"bytes,5,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	EnvId         string                 `protobuf:"bytes,7,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToProjectRes) Reset() {
	*x = AddUserToProjectRes{}
	mi := &file_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToProjectRes) ProtoMessage() {}

func (x *AddUserToProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToProjectRes.ProtoReflect.Descriptor instead.
func (*AddUserToProjectRes) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddUserToProjectRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserToProjectRes) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *AddUserToProjectRes) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddUserToProjectRes) GetTableSlug() string {
	if x != nil {
		return x.TableSlug
	}
	return ""
}

func (x *AddUserToProjectRes) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *AddUserToProjectRes) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AddUserToProjectRes) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type UpsertUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserInfoRequest) Reset() {
	*x = UpsertUserInfoRequest{}
	mi := &file_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserInfoRequest) ProtoMessage() {}

func (x *UpsertUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertUserInfoRequest) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Login                 string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password              string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                 string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                  string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrl              string                 `protobuf:"bytes,6,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	CompanyId             string                 `protobuf:"bytes,7,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,8,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RoleId                string                 `protobuf:"bytes,9,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ClientTypeId          string                 `protobuf:"bytes,10,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	ClientPlatformId      string                 `protobuf:"bytes,11,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Active                int32                  `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	ExpiresAt             string                 `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,14,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	BaseUrl               string                 `protobuf:"bytes,15,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	YearOfBirth           string                 `protobuf:"bytes,16,opt,name=year_of_birth,json=yearOfBirth,proto3" json:"year_of_birth,omitempty"`
	ResourceType          int32                  `protobuf:"varint,17,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Invite                bool                   `protobuf:"varint,18,opt,name=invite,proto3" json:"invite,omitempty"`
	EnvironmentId         string                 `protobuf:"bytes,19,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	NodeType              string                 `protobuf:"bytes,20,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Tin                   string                 `protobuf:"bytes,21,opt,name=tin,proto3" json:"tin,omitempty"`
	AdditionalData        *_struct.Struct        `protobuf:"bytes,22,opt,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *CreateUserRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CreateUserRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateUserRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateUserRequest) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *CreateUserRequest) GetClientPlatformId() string {
	if x != nil {
		return x.ClientPlatformId
	}
	return ""
}

func (x *CreateUserRequest) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *CreateUserRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateUserRequest) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *CreateUserRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateUserRequest) GetYearOfBirth() string {
	if x != nil {
		return x.YearOfBirth
	}
	return ""
}

func (x *CreateUserRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *CreateUserRequest) GetInvite() bool {
	if x != nil {
		return x.Invite
	}
	return false
}

func (x *CreateUserRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CreateUserRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *CreateUserRequest) GetTin() string {
	if x != nil {
		return x.Tin
	}
	return ""
}

func (x *CreateUserRequest) GetAdditionalData() *_struct.Struct {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

type UserPrimaryKey struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,2,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	ResourceType          int32                  `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	IsTest                bool                   `protobuf:"varint,4,opt,name=is_test,json=isTest,proto3" json:"is_test,omitempty"`
	CompanyId             string                 `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientTypeId          string                 `protobuf:"bytes,7,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	NodeType              string                 `protobuf:"bytes,8,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserPrimaryKey) Reset() {
	*x = UserPrimaryKey{}
	mi := &file_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrimaryKey) ProtoMessage() {}

func (x *UserPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrimaryKey.ProtoReflect.Descriptor instead.
func (*UserPrimaryKey) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *UserPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPrimaryKey) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *UserPrimaryKey) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *UserPrimaryKey) GetIsTest() bool {
	if x != nil {
		return x.IsTest
	}
	return false
}

func (x *UserPrimaryKey) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UserPrimaryKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UserPrimaryKey) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *UserPrimaryKey) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type UserPrimaryKeyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ResourceType  int32                  `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	NodeType      string                 `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPrimaryKeyList) Reset() {
	*x = UserPrimaryKeyList{}
	mi := &file_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPrimaryKeyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrimaryKeyList) ProtoMessage() {}

func (x *UserPrimaryKeyList) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrimaryKeyList.ProtoReflect.Descriptor instead.
func (*UserPrimaryKeyList) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *UserPrimaryKeyList) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UserPrimaryKeyList) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UserPrimaryKeyList) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *UserPrimaryKeyList) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type GetUserListRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Limit                 int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset                int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search                string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	ClientPlatformId      string                 `protobuf:"bytes,4,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	ClientTypeId          string                 `protobuf:"bytes,5,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,7,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	ResourceType          int32                  `protobuf:"varint,8,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	NodeType              string                 `protobuf:"bytes,9,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUserListRequest) Reset() {
	*x = GetUserListRequest{}
	mi := &file_user_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRequest) ProtoMessage() {}

func (x *GetUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRequest.ProtoReflect.Descriptor instead.
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUserListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetUserListRequest) GetClientPlatformId() string {
	if x != nil {
		return x.ClientPlatformId
	}
	return ""
}

func (x *GetUserListRequest) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *GetUserListRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetUserListRequest) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *GetUserListRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *GetUserListRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type GetUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users         []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListResponse) Reset() {
	*x = GetUserListResponse{}
	mi := &file_user_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListResponse) ProtoMessage() {}

func (x *GetUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListResponse.ProtoReflect.Descriptor instead.
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetUserListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                 string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                 string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                  string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrl              string                 `protobuf:"bytes,6,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	CompanyId             string                 `protobuf:"bytes,7,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,8,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RoleId                string                 `protobuf:"bytes,9,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ClientTypeId          string                 `protobuf:"bytes,10,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	ClientPlatformId      string                 `protobuf:"bytes,11,opt,name=client_platform_id,json=clientPlatformId,proto3" json:"client_platform_id,omitempty"`
	Active                int32                  `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	ExpiresAt             string                 `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LanguageId            string                 `protobuf:"bytes,14,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	TimezoneId            string                 `protobuf:"bytes,15,opt,name=timezone_id,json=timezoneId,proto3" json:"timezone_id,omitempty"`
	ResourceType          int32                  `protobuf:"varint,16,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,17,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	EnvironmentId         string                 `protobuf:"bytes,18,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	NodeType              string                 `protobuf:"bytes,19,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Status                string                 `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UpdateUserRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateUserRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateUserRequest) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *UpdateUserRequest) GetClientPlatformId() string {
	if x != nil {
		return x.ClientPlatformId
	}
	return ""
}

func (x *UpdateUserRequest) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *UpdateUserRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *UpdateUserRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *UpdateUserRequest) GetTimezoneId() string {
	if x != nil {
		return x.TimezoneId
	}
	return ""
}

func (x *UpdateUserRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *UpdateUserRequest) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *UpdateUserRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *UpdateUserRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddUserRelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId    string                 `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRelationRequest) Reset() {
	*x = AddUserRelationRequest{}
	mi := &file_user_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRelationRequest) ProtoMessage() {}

func (x *AddUserRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRelationRequest.ProtoReflect.Descriptor instead.
func (*AddUserRelationRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{20}
}

func (x *AddUserRelationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserRelationRequest) GetRelationId() string {
	if x != nil {
		return x.RelationId
	}
	return ""
}

func (x *AddUserRelationRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type UserRelationPrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId    string                 `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationPrimaryKey) Reset() {
	*x = UserRelationPrimaryKey{}
	mi := &file_user_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationPrimaryKey) ProtoMessage() {}

func (x *UserRelationPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationPrimaryKey.ProtoReflect.Descriptor instead.
func (*UserRelationPrimaryKey) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{21}
}

func (x *UserRelationPrimaryKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRelationPrimaryKey) GetRelationId() string {
	if x != nil {
		return x.RelationId
	}
	return ""
}

type UserInfoPrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoPrimaryKey) Reset() {
	*x = UserInfoPrimaryKey{}
	mi := &file_user_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoPrimaryKey) ProtoMessage() {}

func (x *UserInfoPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoPrimaryKey.ProtoReflect.Descriptor instead.
func (*UserInfoPrimaryKey) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{22}
}

func (x *UserInfoPrimaryKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfoPrimaryKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Login         string                 `protobuf:"bytes,5,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Tin           string                 `protobuf:"bytes,8,opt,name=tin,proto3" json:"tin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{23}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResetPasswordRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ResetPasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResetPasswordRequest) GetTin() string {
	if x != nil {
		return x.Tin
	}
	return ""
}

type SendMessageToEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	NodeType      string                 `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToEmailRequest) Reset() {
	*x = SendMessageToEmailRequest{}
	mi := &file_user_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToEmailRequest) ProtoMessage() {}

func (x *SendMessageToEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToEmailRequest.ProtoReflect.Descriptor instead.
func (*SendMessageToEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{24}
}

func (x *SendMessageToEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMessageToEmailRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *SendMessageToEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendMessageToEmailRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type V2UserResetPasswordRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OldPassword           string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Password              string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientTypeId          string                 `protobuf:"bytes,4,opt,name=client_type_id,json=clientTypeId,proto3" json:"client_type_id,omitempty"`
	EnvironmentId         string                 `protobuf:"bytes,5,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	NodeType              string                 `protobuf:"bytes,7,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	ResourceEnvironmentId string                 `protobuf:"bytes,8,opt,name=resource_environment_id,json=resourceEnvironmentId,proto3" json:"resource_environment_id,omitempty"`
	ResourceType          int32                  `protobuf:"varint,9,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *V2UserResetPasswordRequest) Reset() {
	*x = V2UserResetPasswordRequest{}
	mi := &file_user_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V2UserResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V2UserResetPasswordRequest) ProtoMessage() {}

func (x *V2UserResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V2UserResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*V2UserResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{25}
}

func (x *V2UserResetPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetClientTypeId() string {
	if x != nil {
		return x.ClientTypeId
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetResourceEnvironmentId() string {
	if x != nil {
		return x.ResourceEnvironmentId
	}
	return ""
}

func (x *V2UserResetPasswordRequest) GetResourceType() int32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

type GetUserProjectClientTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTypeIds []string               `protobuf:"bytes,1,rep,name=client_type_ids,json=clientTypeIds,proto3" json:"client_type_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectClientTypesResponse) Reset() {
	*x = GetUserProjectClientTypesResponse{}
	mi := &file_user_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectClientTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectClientTypesResponse) ProtoMessage() {}

func (x *GetUserProjectClientTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectClientTypesResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectClientTypesResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserProjectClientTypesResponse) GetClientTypeIds() []string {
	if x != nil {
		return x.ClientTypeIds
	}
	return nil
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\fauth_service\x1a\n" +
	"auth.proto\x1a\x14client_service.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"S\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\">\n" +
	"\vUserCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vproject_ids\x18\x02 \x03(\tR\n" +
	"projectIds\"M\n" +
	"\x12GetUserProjectsRes\x127\n" +
	"\tcompanies\x18\x01 \x03(\v2\x19.auth_service.UserCompanyR\tcompanies\"L\n" +
	"\aSetting\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xc4\x01\n" +
	"\x11GetListSettingReq\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.auth_service.SettingTypeR\x04type\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x1b\n" +
	"\tnode_type\x18\x06 \x01(\tR\bnodeType\"\xa3\x02\n" +
	"\x19RegisterWithGoogleRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12$\n" +
	"\x0eclient_type_id\x18\x04 \x01(\tR\fclientTypeId\x126\n" +
	"\x17resource_environment_id\x18\x05 \x01(\tR\x15resourceEnvironmentId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12#\n" +
	"\rresource_type\x18\a \x01(\x05R\fresourceType\x12\x1b\n" +
	"\tnode_type\x18\b \x01(\tR\bnodeType\"6\n" +
	"\x1bGetUserByLoginTypesResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbf\x01\n" +
	"\x1aGetUserByLoginTypesRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\x12#\n" +
	"\rresource_type\x18\x04 \x01(\x05R\fresourceType\x12\x1b\n" +
	"\tnode_type\x18\x05 \x01(\tR\bnodeType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\"N\n" +
	"\x16GetProjectsByUserIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\"C\n" +
	"\vUserProject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x15\n" +
	"\x06env_id\x18\x02 \x01(\tR\x05envId\"X\n" +
	"\x16GetProjectsByUserIdRes\x12>\n" +
	"\ruser_projects\x18\x01 \x03(\v2\x19.auth_service.UserProjectR\fuserProjects\"\xd3\x02\n" +
	"\x13AddUserToProjectReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x16\n" +
	"\x06active\x18\x04 \x01(\x05R\x06active\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tR\tcompanyId\x12#\n" +
	"\rresource_type\x18\x06 \x01(\x05R\fresourceType\x12$\n" +
	"\x0eclient_type_id\x18\a \x01(\tR\fclientTypeId\x12\x1d\n" +
	"\n" +
	"table_slug\x18\b \x01(\tR\ttableSlug\x12\x15\n" +
	"\x06env_id\x18\t \x01(\tR\x05envId\x12\x1b\n" +
	"\tnode_type\x18\n" +
	" \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"\xe1\x01\n" +
	"\x13AddUserToProjectRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"table_slug\x18\x04 \x01(\tR\ttableSlug\x12$\n" +
	"\x0eclient_type_id\x18\x05 \x01(\tR\fclientTypeId\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\tR\x06roleId\x12\x15\n" +
	"\x06env_id\x18\a \x01(\tR\x05envId\"]\n" +
	"\x15UpsertUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xd0\x05\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1b\n" +
	"\tphoto_url\x18\x06 \x01(\tR\bphotoUrl\x12\x1d\n" +
	"\n" +
	"company_id\x18\a \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"project_id\x18\b \x01(\tR\tprojectId\x12\x17\n" +
	"\arole_id\x18\t \x01(\tR\x06roleId\x12$\n" +
	"\x0eclient_type_id\x18\n" +
	" \x01(\tR\fclientTypeId\x12,\n" +
	"\x12client_platform_id\x18\v \x01(\tR\x10clientPlatformId\x12\x16\n" +
	"\x06active\x18\f \x01(\x05R\x06active\x12\x1d\n" +
	"\n" +
	"expires_at\x18\r \x01(\tR\texpiresAt\x126\n" +
	"\x17resource_environment_id\x18\x0e \x01(\tR\x15resourceEnvironmentId\x12\x19\n" +
	"\bbase_url\x18\x0f \x01(\tR\abaseUrl\x12\"\n" +
	"\ryear_of_birth\x18\x10 \x01(\tR\vyearOfBirth\x12#\n" +
	"\rresource_type\x18\x11 \x01(\x05R\fresourceType\x12\x16\n" +
	"\x06invite\x18\x12 \x01(\bR\x06invite\x12%\n" +
	"\x0eenvironment_id\x18\x13 \x01(\tR\renvironmentId\x12\x1b\n" +
	"\tnode_type\x18\x14 \x01(\tR\bnodeType\x12\x10\n" +
	"\x03tin\x18\x15 \x01(\tR\x03tin\x12@\n" +
	"\x0fadditional_data\x18\x16 \x01(\v2\x17.google.protobuf.StructR\x0eadditionalData\"\x97\x02\n" +
	"\x0eUserPrimaryKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x17resource_environment_id\x18\x02 \x01(\tR\x15resourceEnvironmentId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\x05R\fresourceType\x12\x17\n" +
	"\ais_test\x18\x04 \x01(\bR\x06isTest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12$\n" +
	"\x0eclient_type_id\x18\a \x01(\tR\fclientTypeId\x12\x1b\n" +
	"\tnode_type\x18\b \x01(\tR\bnodeType\"\x87\x01\n" +
	"\x12UserPrimaryKeyList\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\x05R\fresourceType\x12\x1b\n" +
	"\tnode_type\x18\x04 \x01(\tR\bnodeType\"\xc7\x02\n" +
	"\x12GetUserListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12,\n" +
	"\x12client_platform_id\x18\x04 \x01(\tR\x10clientPlatformId\x12$\n" +
	"\x0eclient_type_id\x18\x05 \x01(\tR\fclientTypeId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x126\n" +
	"\x17resource_environment_id\x18\a \x01(\tR\x15resourceEnvironmentId\x12#\n" +
	"\rresource_type\x18\b \x01(\x05R\fresourceType\x12\x1b\n" +
	"\tnode_type\x18\t \x01(\tR\bnodeType\"U\n" +
	"\x13GetUserListResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12(\n" +
	"\x05users\x18\x02 \x03(\v2\x12.auth_service.UserR\x05users\"\xf3\x04\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1b\n" +
	"\tphoto_url\x18\x06 \x01(\tR\bphotoUrl\x12\x1d\n" +
	"\n" +
	"company_id\x18\a \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"project_id\x18\b \x01(\tR\tprojectId\x12\x17\n" +
	"\arole_id\x18\t \x01(\tR\x06roleId\x12$\n" +
	"\x0eclient_type_id\x18\n" +
	" \x01(\tR\fclientTypeId\x12,\n" +
	"\x12client_platform_id\x18\v \x01(\tR\x10clientPlatformId\x12\x16\n" +
	"\x06active\x18\f \x01(\x05R\x06active\x12\x1d\n" +
	"\n" +
	"expires_at\x18\r \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vlanguage_id\x18\x0e \x01(\tR\n" +
	"languageId\x12\x1f\n" +
	"\vtimezone_id\x18\x0f \x01(\tR\n" +
	"timezoneId\x12#\n" +
	"\rresource_type\x18\x10 \x01(\x05R\fresourceType\x126\n" +
	"\x17resource_environment_id\x18\x11 \x01(\tR\x15resourceEnvironmentId\x12%\n" +
	"\x0eenvironment_id\x18\x12 \x01(\tR\renvironmentId\x12\x1b\n" +
	"\tnode_type\x18\x13 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\"o\n" +
	"\x16AddUserRelationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vrelation_id\x18\x02 \x01(\tR\n" +
	"relationId\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\"R\n" +
	"\x16UserRelationPrimaryKey\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vrelation_id\x18\x02 \x01(\tR\n" +
	"relationId\"L\n" +
	"\x12UserInfoPrimaryKey\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xd2\x01\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnode_type\x18\x04 \x01(\tR\bnodeType\x12\x14\n" +
	"\x05login\x18\x05 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x10\n" +
	"\x03tin\x18\b \x01(\tR\x03tin\"\x7f\n" +
	"\x19SendMessageToEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1b\n" +
	"\tnode_type\x18\x04 \x01(\tR\bnodeType\"\xda\x02\n" +
	"\x1aV2UserResetPasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12$\n" +
	"\x0eclient_type_id\x18\x04 \x01(\tR\fclientTypeId\x12%\n" +
	"\x0eenvironment_id\x18\x05 \x01(\tR\renvironmentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tnode_type\x18\a \x01(\tR\bnodeType\x126\n" +
	"\x17resource_environment_id\x18\b \x01(\tR\x15resourceEnvironmentId\x12#\n" +
	"\rresource_type\x18\t \x01(\x05R\fresourceType\"K\n" +
	"!GetUserProjectClientTypesResponse\x12&\n" +
	"\x0fclient_type_ids\x18\x01 \x03(\tR\rclientTypeIds*)\n" +
	"\vSettingType\x12\f\n" +
	"\bLANGUAGE\x10\x00\x12\f\n" +
	"\bTIMEZONE\x10\x022\xd5\x11\n" +
	"\vUserService\x12C\n" +
	"\n" +
	"CreateUser\x12\x1f.auth_service.CreateUserRequest\x1a\x12.auth_service.User\"\x00\x12A\n" +
	"\vGetUserByID\x12\x1c.auth_service.UserPrimaryKey\x1a\x12.auth_service.User\"\x00\x12Y\n" +
	"\x10GetUserListByIDs\x12 .auth_service.UserPrimaryKeyList\x1a!.auth_service.GetUserListResponse\"\x00\x12T\n" +
	"\vGetUserList\x12 .auth_service.GetUserListRequest\x1a!.auth_service.GetUserListResponse\"\x00\x12C\n" +
	"\n" +
	"UpdateUser\x12\x1f.auth_service.UpdateUserRequest\x1a\x12.auth_service.User\"\x00\x12D\n" +
	"\n" +
	"DeleteUser\x12\x1c.auth_service.UserPrimaryKey\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\rResetPassword\x12\".auth_service.ResetPasswordRequest\x1a\x12.auth_service.User\"\x00\x12W\n" +
	"\x12SendMessageToEmail\x12'.auth_service.SendMessageToEmailRequest\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x0fAddUserRelation\x12$.auth_service.AddUserRelationRequest\x1a\x1a.auth_service.UserRelation\"\x00\x12X\n" +
	"\x12RemoveUserRelation\x12$.auth_service.UserRelationPrimaryKey\x1a\x1a.auth_service.UserRelation\"\x00\x12O\n" +
	"\x0eUpsertUserInfo\x12#.auth_service.UpsertUserInfoRequest\x1a\x16.auth_service.UserInfo\"\x00\x12E\n" +
	"\fV2CreateUser\x12\x1f.auth_service.CreateUserRequest\x1a\x12.auth_service.User\"\x00\x12C\n" +
	"\rV2GetUserByID\x12\x1c.auth_service.UserPrimaryKey\x1a\x12.auth_service.User\"\x00\x12[\n" +
	"\x12V2GetUserListByIDs\x12 .auth_service.UserPrimaryKeyList\x1a!.auth_service.GetUserListResponse\"\x00\x12V\n" +
	"\rV2GetUserList\x12 .auth_service.GetUserListRequest\x1a!.auth_service.GetUserListResponse\"\x00\x12E\n" +
	"\fV2UpdateUser\x12\x1f.auth_service.UpdateUserRequest\x1a\x12.auth_service.User\"\x00\x12F\n" +
	"\fV2DeleteUser\x12\x1c.auth_service.UserPrimaryKey\x1a\x16.google.protobuf.Empty\"\x00\x12Q\n" +
	"\x0fV2ResetPassword\x12(.auth_service.V2UserResetPasswordRequest\x1a\x12.auth_service.User\"\x00\x12Z\n" +
	"\x10AddUserToProject\x12!.auth_service.AddUserToProjectReq\x1a!.auth_service.AddUserToProjectRes\"\x00\x12c\n" +
	"\x13GetProjectsByUserId\x12$.auth_service.GetProjectsByUserIdReq\x1a$.auth_service.GetProjectsByUserIdRes\"\x00\x12n\n" +
	"\x15V2GetUserByLoginTypes\x12(.auth_service.GetUserByLoginTypesRequest\x1a).auth_service.GetUserByLoginTypesResponse\"\x00\x12M\n" +
	"\x14RegisterUserViaEmail\x12\x1f.auth_service.CreateUserRequest\x1a\x12.auth_service.User\"\x00\x12S\n" +
	"\x12RegisterWithGoogle\x12'.auth_service.RegisterWithGoogleRequest\x1a\x12.auth_service.User\"\x00\x12J\n" +
	"\x0eGetListSetting\x12\x1f.auth_service.GetListSettingReq\x1a\x15.auth_service.Setting\"\x00\x12Q\n" +
	"\x11GetUserByUsername\x12&.auth_service.GetUserByUsernameRequest\x1a\x12.auth_service.User\"\x00\x12S\n" +
	"\x0fGetUserProjects\x12\x1c.auth_service.UserPrimaryKey\x1a .auth_service.GetUserProjectsRes\"\x00\x12p\n" +
	"\x19GetUserProjectClientTypes\x12 .auth_service.UserInfoPrimaryKey\x1a/.auth_service.GetUserProjectClientTypesResponse\"\x00B\x17Z\x15genproto/auth_serviceb\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_user_service_proto_goTypes = []any{
	(SettingType)(0),                          // 0: auth_service.SettingType
	(*GetUserByUsernameRequest)(nil),          // 1: auth_service.GetUserByUsernameRequest
	(*UserCompany)(nil),                       // 2: auth_service.UserCompany
	(*GetUserProjectsRes)(nil),                // 3: auth_service.GetUserProjectsRes
	(*Setting)(nil),                           // 4: auth_service.Setting
	(*GetListSettingReq)(nil),                 // 5: auth_service.GetListSettingReq
	(*RegisterWithGoogleRequest)(nil),         // 6: auth_service.RegisterWithGoogleRequest
	(*GetUserByLoginTypesResponse)(nil),       // 7: auth_service.GetUserByLoginTypesResponse
	(*GetUserByLoginTypesRequest)(nil),        // 8: auth_service.GetUserByLoginTypesRequest
	(*GetProjectsByUserIdReq)(nil),            // 9: auth_service.GetProjectsByUserIdReq
	(*UserProject)(nil),                       // 10: auth_service.UserProject
	(*GetProjectsByUserIdRes)(nil),            // 11: auth_service.GetProjectsByUserIdRes
	(*AddUserToProjectReq)(nil),               // 12: auth_service.AddUserToProjectReq
	(*AddUserToProjectRes)(nil),               // 13: auth_service.AddUserToProjectRes
	(*UpsertUserInfoRequest)(nil),             // 14: auth_service.UpsertUserInfoRequest
	(*CreateUserRequest)(nil),                 // 15: auth_service.CreateUserRequest
	(*UserPrimaryKey)(nil),                    // 16: auth_service.UserPrimaryKey
	(*UserPrimaryKeyList)(nil),                // 17: auth_service.UserPrimaryKeyList
	(*GetUserListRequest)(nil),                // 18: auth_service.GetUserListRequest
	(*GetUserListResponse)(nil),               // 19: auth_service.GetUserListResponse
	(*UpdateUserRequest)(nil),                 // 20: auth_service.UpdateUserRequest
	(*AddUserRelationRequest)(nil),            // 21: auth_service.AddUserRelationRequest
	(*UserRelationPrimaryKey)(nil),            // 22: auth_service.UserRelationPrimaryKey
	(*UserInfoPrimaryKey)(nil),                // 23: auth_service.UserInfoPrimaryKey
	(*ResetPasswordRequest)(nil),              // 24: auth_service.ResetPasswordRequest
	(*SendMessageToEmailRequest)(nil),         // 25: auth_service.SendMessageToEmailRequest
	(*V2UserResetPasswordRequest)(nil),        // 26: auth_service.V2UserResetPasswordRequest
	(*GetUserProjectClientTypesResponse)(nil), // 27: auth_service.GetUserProjectClientTypesResponse
	(*_struct.Struct)(nil),                    // 28: google.protobuf.Struct
	(*User)(nil),                              // 29: auth_service.User
	(*empty.Empty)(nil),                       // 30: google.protobuf.Empty
	(*UserRelation)(nil),                      // 31: auth_service.UserRelation
	(*UserInfo)(nil),                          // 32: auth_service.UserInfo
}
var file_user_service_proto_depIdxs = []int32{
	2,  // 0: auth_service.GetUserProjectsRes.companies:type_name -> auth_service.UserCompany
	28, // 1: auth_service.Setting.data:type_name -> google.protobuf.Struct
	0,  // 2: auth_service.GetListSettingReq.type:type_name -> auth_service.SettingType
	10, // 3: auth_service.GetProjectsByUserIdRes.user_projects:type_name -> auth_service.UserProject
	28, // 4: auth_service.UpsertUserInfoRequest.data:type_name -> google.protobuf.Struct
	28, // 5: auth_service.CreateUserRequest.additional_data:type_name -> google.protobuf.Struct
	29, // 6: auth_service.GetUserListResponse.users:type_name -> auth_service.User
	15, // 7: auth_service.UserService.CreateUser:input_type -> auth_service.CreateUserRequest
	16, // 8: auth_service.UserService.GetUserByID:input_type -> auth_service.UserPrimaryKey
	17, // 9: auth_service.UserService.GetUserListByIDs:input_type -> auth_service.UserPrimaryKeyList
	18, // 10: auth_service.UserService.GetUserList:input_type -> auth_service.GetUserListRequest
	20, // 11: auth_service.UserService.UpdateUser:input_type -> auth_service.UpdateUserRequest
	16, // 12: auth_service.UserService.DeleteUser:input_type -> auth_service.UserPrimaryKey
	24, // 13: auth_service.UserService.ResetPassword:input_type -> auth_service.ResetPasswordRequest
	25, // 14: auth_service.UserService.SendMessageToEmail:input_type -> auth_service.SendMessageToEmailRequest
	21, // 15: auth_service.UserService.AddUserRelation:input_type -> auth_service.AddUserRelationRequest
	22, // 16: auth_service.UserService.RemoveUserRelation:input_type -> auth_service.UserRelationPrimaryKey
	14, // 17: auth_service.UserService.UpsertUserInfo:input_type -> auth_service.UpsertUserInfoRequest
	15, // 18: auth_service.UserService.V2CreateUser:input_type -> auth_service.CreateUserRequest
	16, // 19: auth_service.UserService.V2GetUserByID:input_type -> auth_service.UserPrimaryKey
	17, // 20: auth_service.UserService.V2GetUserListByIDs:input_type -> auth_service.UserPrimaryKeyList
	18, // 21: auth_service.UserService.V2GetUserList:input_type -> auth_service.GetUserListRequest
	20, // 22: auth_service.UserService.V2UpdateUser:input_type -> auth_service.UpdateUserRequest
	16, // 23: auth_service.UserService.V2DeleteUser:input_type -> auth_service.UserPrimaryKey
	26, // 24: auth_service.UserService.V2ResetPassword:input_type -> auth_service.V2UserResetPasswordRequest
	12, // 25: auth_service.UserService.AddUserToProject:input_type -> auth_service.AddUserToProjectReq
	9,  // 26: auth_service.UserService.GetProjectsByUserId:input_type -> auth_service.GetProjectsByUserIdReq
	8,  // 27: auth_service.UserService.V2GetUserByLoginTypes:input_type -> auth_service.GetUserByLoginTypesRequest
	15, // 28: auth_service.UserService.RegisterUserViaEmail:input_type -> auth_service.CreateUserRequest
	6,  // 29: auth_service.UserService.RegisterWithGoogle:input_type -> auth_service.RegisterWithGoogleRequest
	5,  // 30: auth_service.UserService.GetListSetting:input_type -> auth_service.GetListSettingReq
	1,  // 31: auth_service.UserService.GetUserByUsername:input_type -> auth_service.GetUserByUsernameRequest
	16, // 32: auth_service.UserService.GetUserProjects:input_type -> auth_service.UserPrimaryKey
	23, // 33: auth_service.UserService.GetUserProjectClientTypes:input_type -> auth_service.UserInfoPrimaryKey
	29, // 34: auth_service.UserService.CreateUser:output_type -> auth_service.User
	29, // 35: auth_service.UserService.GetUserByID:output_type -> auth_service.User
	19, // 36: auth_service.UserService.GetUserListByIDs:output_type -> auth_service.GetUserListResponse
	19, // 37: auth_service.UserService.GetUserList:output_type -> auth_service.GetUserListResponse
	29, // 38: auth_service.UserService.UpdateUser:output_type -> auth_service.User
	30, // 39: auth_service.UserService.DeleteUser:output_type -> google.protobuf.Empty
	29, // 40: auth_service.UserService.ResetPassword:output_type -> auth_service.User
	30, // 41: auth_service.UserService.SendMessageToEmail:output_type -> google.protobuf.Empty
	31, // 42: auth_service.UserService.AddUserRelation:output_type -> auth_service.UserRelation
	31, // 43: auth_service.UserService.RemoveUserRelation:output_type -> auth_service.UserRelation
	32, // 44: auth_service.UserService.UpsertUserInfo:output_type -> auth_service.UserInfo
	29, // 45: auth_service.UserService.V2CreateUser:output_type -> auth_service.User
	29, // 46: auth_service.UserService.V2GetUserByID:output_type -> auth_service.User
	19, // 47: auth_service.UserService.V2GetUserListByIDs:output_type -> auth_service.GetUserListResponse
	19, // 48: auth_service.UserService.V2GetUserList:output_type -> auth_service.GetUserListResponse
	29, // 49: auth_service.UserService.V2UpdateUser:output_type -> auth_service.User
	30, // 50: auth_service.UserService.V2DeleteUser:output_type -> google.protobuf.Empty
	29, // 51: auth_service.UserService.V2ResetPassword:output_type -> auth_service.User
	13, // 52: auth_service.UserService.AddUserToProject:output_type -> auth_service.AddUserToProjectRes
	11, // 53: auth_service.UserService.GetProjectsByUserId:output_type -> auth_service.GetProjectsByUserIdRes
	7,  // 54: auth_service.UserService.V2GetUserByLoginTypes:output_type -> auth_service.GetUserByLoginTypesResponse
	29, // 55: auth_service.UserService.RegisterUserViaEmail:output_type -> auth_service.User
	29, // 56: auth_service.UserService.RegisterWithGoogle:output_type -> auth_service.User
	4,  // 57: auth_service.UserService.GetListSetting:output_type -> auth_service.Setting
	29, // 58: auth_service.UserService.GetUserByUsername:output_type -> auth_service.User
	3,  // 59: auth_service.UserService.GetUserProjects:output_type -> auth_service.GetUserProjectsRes
	27, // 60: auth_service.UserService.GetUserProjectClientTypes:output_type -> auth_service.GetUserProjectClientTypesResponse
	34, // [34:61] is the sub-list for method output_type
	7,  // [7:34] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	file_auth_proto_init()
	file_client_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		EnumInfos:         file_user_service_proto_enumTypes,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
